### PR TITLE
Docker 1.12: handle daemon named 'dockerd'

### LINKED ISSUE #2379: Docker 1.12 breaks Weave
(as of 1.12.0-rc1)
The daemon now runs as a process called `dockerd`, which breaks `docker-tls-args` which is looking for `docker -d`.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #2379

### CODE REVIEW

**Comment by rade** [comment]
This should be on the 1.5 branch.

**Comment by awh** [comment]
LGTM. Quick aside - this

https://github.com/weaveworks/weave/pull/2380/files#diff-5fb26b2385c2ea3455765e854c85c607R50

`break` statement is redundant isn't it?

Did you want to retarget this at the 1.5 branch?

**Comment by bboreham** [comment]
I imagine that `break` statement was meant to end the loop, but it doesn't.  

However, if we did make it break the loop, I suspect we could mistake a `docker run -d` command for the daemon process.

**Comment by bboreham** [comment]
Replaced by #2382 on 1.5 branch

**Comment by bboreham** [comment]
Changed my mind: the `break` is just superfluous

**Pull request closed without merging**
