### PR TITLE
Use Boostrap styles for warnings in docs

### LINKED ISSUE #1061: improve blockquote rendering
http://docs.weave.works/weave/latest_release/weavedns.html#usage - the markdown blockquote in that is rendered rather oddly.

@davkal

### PR DESCRIPTION
**Pull request by davkal**
Instead of using `> ` for warnings in the docs, we'll use 
```html
<div class="alert alert-warning">
Crazy stuff happening...
</div>
```

Fixes #1061

### CODE REVIEW

**Comment by rade** [comment]
I don't really like this. Makes the markdown less readable. Can't we have some CSS for rendering markdown blockquotes?

**Comment by davkal** [comment]
Ok, I mean, abusing blockquote that way isnt exactly clean, either. What if someone really wants to quote?
But I can be convinced by the fact that mixing html and markdown is a tinge dirtier, still. I'll try a CSS based solution.

**Comment by rade** [comment]
> What if someone really wants to quote?

Ideally the resulting style would work for both quotes and "important info". So shouldn't be too shrill. No red, bold, flashing blobs :)

**Comment by davkal** [comment]
screen shot 2015-07-17 at 14 15 39
Going with the bootstrap alert style, but overriding blockquote styling.

**Comment by rade** [comment]
Looks fine to me.

**Comment by davkal** [comment]
Cool, I just pushed the fix. Original implementation is in website repo, copied compiled css over to here and added `?v=1` to css link as a browser cache buster.

Ready for review.

**Pull request merged**
