### PR TITLE
Make Weave build & work with Go 1.5

### PR DESCRIPTION
**Pull request by tomwilkie**
FIxes:

```
go get ./prog/weavewait
go install net: open /usr/local/go/pkg/linux_amd64/net.a: permission denied
make: *** [prog/weavewait/weavewait] Error 1
```

And:

```
# github.com/weaveworks/weave/prog/weaver
link: warning: option -X main.version git-4c6a8f29c0ea may not work in future releases; use -X main.version=git-4c6a8f29c0ea
```

TODO:
- Update circle to install go1.5

### CODE REVIEW

**Comment by tomwilkie** [comment]
Also fixes
```
vagrant@ubuntu-14:~/src/github.com/weaveworks/scope/experimental/example$ docker run -d --name=elasticsearch1 --hostname=elasticsearch.weave.local elasticsearch
d7dc75438f58638136f9be1364f604532d4d19845addbfbb69d43244f8495251
Error response from daemon: ./weave: line 1625: weavehosts: not found
```

Caused by weavehosts not be statically linked.

**Comment by dpw** [comment]
build/dockerfile should not be changed to use 1.5, unless we are making a decision as a team to make 1.5 our recommended golang version, and all use 1.5 for development henceforth.  Otherwise, it should be left at 1.4, in order to make sure that we do not write code that depends on 1.5.

**Comment by tomwilkie** [comment]
@dpw PTAL

**Comment by dpw** [comment]
Should this issue cover making weave work with 1.5, or is it just build issues?  (I'm thinking of #1393)

**Comment by rade** [comment]
> Should this issue cover making weave work with 1.5, or is it just build issues?

As long as this PR doesn't entail switching to 1.5 for builds, then I think it's ok to handle runtime issues separately.

**Comment by dpw** [comment]
> As long as this PR doesn't entail switching to 1.5 for builds, then I think it's ok to handle runtime issues separately.

Ok.  But we might as well fix obvious breakage, right?  I'll add my fix.

I've checked that Tom's changes don't break builds with 1.4.  I'll find out what the plan for this PR is tomorrow (not sure what the "WIP" signifies).

**Comment by tomwilkie** [comment]
Wip means work in progress but it can be removed now.

**Comment by dpw** [comment]
Just tested with go-1.5.1.

**Comment by rade** [comment]
This got reverted in 12324e35 because of #1412.

**Comment by dpw** [comment]
I reverted Tom's commit to address #1412.

**Pull request merged**
