### PR TITLE
Implement `weave consense`

### LINKED ISSUE #1994: Add facility to force IPAM consensus on a node
To make certain operational processes (e.g. extending a cluster) safe we need a way to force and wait for consensus on a specific node.

### PR DESCRIPTION
**Pull request by awh**
Fixes #1994.

### CODE REVIEW

**Comment by bboreham** [comment]
I rebased this against master

**Comment by awh** [comment]
> I rebased this against master

Any comments @bboreham?

Docs deliberately missing from this PR to avoid clashing with the documentation restructuring - will add some after that has merged.

**Comment by rade** [comment]
> Docs deliberately missing from this PR to avoid clashing with the documentation restructuring - will add some after that has merged.

Please don't defer updating the docs.

**Comment by bboreham** [comment]
I guess we could have done this with a dummy allocation for a zero-size range, to avoid a new queue and data type.

But no specific complaints about the way you did it.

**Comment by awh** [comment]
> I guess we could have done this with a dummy allocation for a zero-size range, to avoid a new queue and data type.

I did consider it, but I felt it was cleaner to have a proper operation for it.

Rebased on master + added some docs.

**Pull request merged**
