### PR TITLE
In IPAM, resurrect apparently-dead containers on ContainerStarted event

### PR DESCRIPTION
**Pull request by bboreham**
Partial fix for #1179

### CODE REVIEW

**Comment by rade** [comment]
> Partial

Please elaborate.

**Comment by bboreham** [comment]
> only for IPAM, not DNS. It also creates a situation where a container that restarts quickly retains all its IPAM [records], but one that gets stopped and started the next day loses all additional records created via weave attach

**Comment by rade** [comment]
There is something weird going on with this. With [the patch from the issue](https://github.com/weaveworks/weave/issues/1179#issuecomment-179820559), I get...

```
$ weave launch
$ eval $(weave env)
$ docker run --name=foo -dti ubuntu
eeb9a94dffce787d1a5685dbf333212342c39f066933a01b774f306f8478fc29
$ docker restart foo; weave ps; weave status dns; sleep 40; docker run --name=bar -dti ubuntu; weave ps; weave status dns
foo
weave:expose d2:e2:3d:cc:92:05
eeb9a94dffce 42:cf:7e:b5:ce:c3 10.32.0.1/12
foo          10.32.0.1       eeb9a94dffce d2:e2:3d:cc:92:05
23fe25e509c8426b7a25a4768215e3584c2932a21d83ce2fd49d9203437e4443
weave:expose d2:e2:3d:cc:92:05
23fe25e509c8 ae:e0:a9:c7:e0:0c 10.32.0.2/12
eeb9a94dffce 42:cf:7e:b5:ce:c3 10.32.0.1/12
bar          10.32.0.2       23fe25e509c8 d2:e2:3d:cc:92:05
```
What happened to foo's DNS entry?

Note that the patch only delays the delivery of `ContainerDied`

**Comment by bboreham** [comment]
The weird thing going on is that the transport of events via `fsouza/go-dockerclient` is done on separate goroutines for each listener (and our IPAM and DNS are two listeners), but the whole thing will lock up if the chan for one listener blocks.

And, it is nondeterministic whether it locks up before or after the DNS event is delivered.

**Pull request merged**
