### PR TITLE
correct RFC3484 address selection caveat

### LINKED ISSUE #1710: Load-balancing description needs updating
The wording of https://github.com/weaveworks/weave/pull/1256, particularly "on the local machine", needs to be updated in view of the findings at https://github.com/weaveworks/guides/issues/133#issuecomment-158964627

### PR DESCRIPTION
**Pull request by rade**
and move it to a more prominent location

Fixes #1710

### CODE REVIEW

**Comment by rade** [comment]
cc @abuehrle

**Comment by bboreham** [comment]
LGTM

**Comment by abuehrle** [comment]
LGTM

**Comment by rade** [comment]
This PR was created against master instead of 1.6. I've fixed that by merging the branch into 1.6 and that into master.

**Pull request merged**
