### PR TITLE
New test image using docker 1.8

### LINKED ISSUE #1433: Update GCE images to use Docker 1.8.2

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #1433

### CODE REVIEW

**Comment by tomwilkie** [comment]
Have updated to 1.8.2, but 601_proxy_docker_py_test.sh and 160_claim_3_test.sh are still failing.

**Comment by tomwilkie** [comment]
Note the failing py test is TestExecuteCommandStringAsUser, not CreateContainerWithGroupAddTest as in #1437

**Comment by rade** [comment]
> Note the failing py test is TestExecuteCommandStringAsUser

we've seen this fail before, e.g. https://circleci.com/gh/weaveworks/weave/2910 4 days ago. But it fixed itself two days ago in https://circleci.com/gh/weaveworks/weave/2913. Weird.

**Comment by tomwilkie** [comment]
Good to know its not related.  Shall we stick this in a raise a different bug for the new failure?  Its hard for me to reproduce from here - high latency to gce.

**Comment by rade** [comment]
> Shall we raise a different bug

yes.

**Comment by rade** [comment]
LGTM

**Comment by rade** [comment]
#1467 incorporated this same change into 1.1.

**Pull request merged**
