### PR TITLE
Fast datapath compatibility with 1.1

### PR DESCRIPTION
**Pull request by dpw**
This is stacked on top of the fdp-rebase branch, so should not be merged until after #1438.

Addresses #1448.  Compatibility with 1.1 is intended to "just work", so that we won't need to explain any special procedure for doing rolling upgrades to 1.2.

### CODE REVIEW

**Comment by awh** [comment]
It'd be nice to have a smoketest to prove the compatibility works - it would be trivial if not for the fact that one of the VMs needs to be downgraded to a release version of weave for the test in question - I'll see if I can think of a way to do that cleanly. No comments otherwise, ready to merge.

**Comment by rade** [comment]
All that +/-1 is rather tedious. Wouldn't it be simpler to just give up one id, i.e. have them range from 1 to 4095?

**Comment by dpw** [comment]
> All that +/-1 is rather tedious. Wouldn't it be simpler to just give up one id, i.e. have them range from 1 to 4095?

That would eliminate the +1/-1 mapping in fastdp.go, but lead to other +1/-1 popping up in the places where we generate random short ids.  Actually, the impact on randomPeerShortID would be worse, because currently it masks a randomUint16().

**Comment by rade** [comment]
> the places where we generate random short ids

afaict there are two functions - `Peers.chooseShortID` and `randomPeerShortyID` - that would be affected. These are *already* affected by the +/-1 change. Yes, the code to produce random numbers in the range 1-4095 is more complicated than for 0-4095, but it would eliminate the +/-1 in the fastdp code.

**Comment by dpw** [comment]
Sounds like a cartoon where they push down on a lump under the carpet, and another lump pops up elsewhere.

There's another approach that might turn out tidier: Add a `HasShortID` bool field to `Peer`, always setting it to true in `NewPeer`.  Any `Peer` with it set to false is one that came from a 1.1 peer.  Then the range of `ShortID` wouldn't need any adjustment.

I can't think of any gotchas right now, I'll look at it more tomorrow.

(And with some care, that `HasShortID` field could be retired eventually.)

**Comment by rade** [comment]
somewhat pertinent... the addition of `ShortID` to `Peer` is unfortunate; it is the *only* field in `Peer` - and topology gossip overall - that is specific to the overlay. It has nothing to do with the control plane as such. I'm trying hard to think of it in generic terms ("there is nothing peculiar about wanting each peer in your system to have a short id"), but it's a struggle ;)

**Comment by awh** [comment]
Can this change not be reverted for 1.3?

**Comment by dpw** [comment]
> somewhat pertinent...

I don't think it's pertinent to this issue - it's certainly not something to be addressed as part of this compat work.  It may be pertinent to the main fastdp issue, so if you want to raise it, I suggest raising it there.  (But that has been in a "for review" state for a couple of weeks now.  And the ShortID code was in something very close to its present state in the fastdp preview a few months ago.  This seems like an odd time to take an interest in it.)

> the addition of ShortID to Peer is unfortunate; it is the only field in Peer - and topology gossip overall - that is specific to the overlay. It has nothing to do with the control plane as such. I'm trying hard to think of it in generic terms ("there is nothing peculiar about wanting each peer in your system to have a short id"), but it's a struggle

I don't greatly disagree.  You probably won't be surprised to hear that there are many aspects of the fastdp code I remain unsatisfied with, and this is one.  It is the something specific to the fastdp overlay that leaks out.  But, my aim in the fastdp work has been that it should become a key part of Weave Net, so it is questionable how much it matters that it is not structured as a pure "bolt on extra" to the rest of the codebase.  The perfect is the enemy of the good; perhaps the ShortID is glaring simply because the overlay code now has a modular structure.  Given how prolonged the merge process for that has been, I'm not sure it would have been viable to extend the scope of the fastdp effort further, and I'm not sure exactly what your intent is.

**Comment by dpw** [comment]
> Can this change not be reverted for 1.3?

Some parts yes, some parts no.  There is no intention that these commits can simply be reverted.  Where we can do things now which make a real difference to the possibility of simplifying the code in later releases, that's good. And I have ideas about how I would go about those simplifications, some of which I described in the associated issue (largely for my own reference; I'm not sure how intelligible the description was to others). But I don't think it is worth doing work now that can just as well, and perhaps better, be done later.

**Comment by rade** [comment]
@dpw I certainly wasn't suggesting that we hold up merging of fdp; I only mentioned the `ShortID` issue in case you could think of a quick fix but also because adding `HasShortID` arguably makes the situation worse.

**Comment by awh** [comment]
> > Wouldn't it be simpler to just give up one id, i.e. have them range from 1 to 4095?

> Sounds like a cartoon where they push down on a lump under the carpet, and another lump pops up elsewhere.

Except that if you did as Matthias suggested, it would eliminate the offset in the VNI to ShortID mapping, which would mean (I think) that the only consequence of completely reverting the reservation of ShortID zero in 1.3 would be that a new peer which happened to choose zero for itself would be unreachable by existing peers until they were restarted.

**Comment by awh** [comment]
> which would mean (I think) that the only consequence of completely reverting the reservation of ShortID zero in 1.3 would be that a new peer which happened to choose zero for itself would be unreachable by existing peers until they were restarted.

Is this right, and if so, do you consider the consequence tolerable as part of a rolling upgrade?

**Comment by dpw** [comment]
> Is this right, and if so, do you consider the consequence tolerable as part of a rolling upgrade?

As you two seem determined to make a fuss about the +1/-1 in fastdp.go, I'm implementing my `HasShortID` proposal, which doesn't add a +1 or a -1 anywhere.

**Comment by dpw** [comment]
Revised.

**Pull request merged**
