### PR TITLE
Add two functions required by ipamapi "contract"

### LINKED ISSUE #1984: 1.4 build broken due to change in libnetwork IPAM API
[https://travis-ci.org/weaveworks/weave/builds/110119762#L369]

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #1984

### CODE REVIEW

**Comment by rade** [comment]
I notice we have
```
	DiscoverNew(discover *api.DiscoveryNotification) error
	DiscoverDelete(delete *api.DiscoveryNotification) error
```
in our (network) `Driver` interface. And have `discoverNew` and `discoverDelete` methods on the `listener` that call them. But they are not wired into the http method handling.

Cruft?

**Comment by bboreham** [comment]
Well, having them in the interface is plausible, since they were in Docker's `Driver` interface (refactored by https://github.com/docker/libnetwork/commit/94e4e395c5dad83e882e99781bcd7c1ce8aca4e8)

Not wiring them into the http mux seems like a mistake.

Also the spelling error in their log-lines.

**Comment by bboreham** [comment]
Following https://github.com/docker/libnetwork/pull/908#issuecomment-185810190 I guess this 'fix' is now a mistake.

**Comment by rade** [comment]
quite. let's see how that resolves itself in the end. we should probably also check/ask about the network driver api.

**Comment by mavenugo** [comment]
@bboreham sorry about the breakage. We are recommending for plugins to use `https://github.com/docker/go-plugins-helpers/` for any docker plugin development. Can you please migrate to using these APIs instead of depending the libnetwork/ipamapi layer ?

**Comment by rade** [comment]
@mavenugo sure, can do!

**Comment by rade** [comment]
I am merging this as is since switching the dependencies is too much of a leap for a patch release.

I have raised #1986 to fix this properly.

**Comment by bboreham** [comment]
@mavenugo where exactly was this publicised/recommended? I missed it.

**Comment by rade** [comment]
@mavenugo AFAICT, go-plugins-helpers does not allow one to serve multiple APIs, e.g. networking and ipam, on the same listener. This is something the plugin API spec permits and we depend on. Did I miss something in my reading of the plugins-helpers code?

**Pull request merged**
