### PR TITLE
Script to list versions of Go, Docker, Kubernetes

### LINKED ISSUE #2664: Script to list versions of Go, Docker, Kubernetes
As part of #2647, we need a way to list all versions of Weave Net's dependencies:
* Go
* Docker
* Kubernetes

in various ways:
* releases only
* releases and latest release candidate

### PR DESCRIPTION
**Pull request by marccarre**
Fixes #2664.

### CODE REVIEW

**Comment by marccarre** [comment]
Get versions of Go:

1. Get released versions of Go using Python2
```
$ python2 ./build/scripts/list_versions.py go
1
1.0.1
1.0.2
1.0.3
1.1
1.1.1
1.1.2
1.2
1.2.1
1.2.2
1.3
1.3.1
1.3.2
1.3.3
1.4
1.4.1
1.4.2
1.4.3
1.5
1.5.1
1.5.2
1.5.3
1.5.4
1.6
1.6.1
1.6.2
1.6.3
1.7
1.7.1
1.7.2
1.7.3
$ echo $?
0
```
2. Get released versions of Go using Python3
```
$ python3 ./build/scripts/list_versions.py go
1
1.0.1
1.0.2
1.0.3
1.1
1.1.1
1.1.2
1.2
1.2.1
1.2.2
1.3
1.3.1
1.3.2
1.3.3
1.4
1.4.1
1.4.2
1.4.3
1.5
1.5.1
1.5.2
1.5.3
1.5.4
1.6
1.6.1
1.6.2
1.6.3
1.7
1.7.1
1.7.2
1.7.3
$ echo $?
0
```
3. Get released versions and latest release candidate of Go using Python2
```
$ python2 ./build/scripts/list_versions.py --include-rc go
1
1.0.1
1.0.2
1.0.3
1.1
1.1.1
1.1.2
1.2
1.2.1
1.2.2
1.3
1.3.1
1.3.2
1.3.3
1.4
1.4.1
1.4.2
1.4.3
1.5
1.5.1
1.5.2
1.5.3
1.5.4
1.6
1.6.1
1.6.2
1.6.3
1.7
1.7.1
1.7.2
1.7.3
1.7rc6
$ echo $?
0
```
4. Get released versions and latest release candidate of Go using Python2
```
$ python3 ./build/scripts/list_versions.py --include-rc go
1
1.0.1
1.0.2
1.0.3
1.1
1.1.1
1.1.2
1.2
1.2.1
1.2.2
1.3
1.3.1
1.3.2
1.3.3
1.4
1.4.1
1.4.2
1.4.3
1.5
1.5.1
1.5.2
1.5.3
1.5.4
1.6
1.6.1
1.6.2
1.6.3
1.7
1.7.1
1.7.2
1.7.3
1.7rc6
$ echo $?
0
```

**Comment by marccarre** [comment]
Get versions of Docker:

1. Get released versions of Docker using Python2
```
$ python2 ./build/scripts/list_versions.py docker
1.6.0
1.6.1
1.6.2
1.7.0
1.7.1
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
1.11.0
1.11.1
1.11.2
1.12.0
1.12.1
1.12.2
1.12.3
$ echo $?
0
```
2. Get released versions of Docker using Python3
```
$ python3 ./build/scripts/list_versions.py docker
1.6.0
1.6.1
1.6.2
1.7.0
1.7.1
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
1.11.0
1.11.1
1.11.2
1.12.0
1.12.1
1.12.2
1.12.3
$ echo $?
0
```
3. Get released versions and latest release candidate of Docker using Python2
```
$ python2 ./build/scripts/list_versions.py --include-rc docker
1.6.0
1.6.1
1.6.2
1.7.0
1.7.1
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
1.11.0
1.11.1
1.11.2
1.12.0
1.12.1
1.12.2
1.12.3
1.13.0-rc1
$ echo $?
0
```
4. Get released versions and latest release candidate of Docker using Python3
```
$ python3 ./build/scripts/list_versions.py --include-rc docker
1.6.0
1.6.1
1.6.2
1.7.0
1.7.1
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
1.11.0
1.11.1
1.11.2
1.12.0
1.12.1
1.12.2
1.12.3
1.13.0-rc1
$ echo $?
0
```

**Comment by marccarre** [comment]
Get versions of Kubernetes:

1. Get released versions of Kubernetes using Python2
```
$ python2 ./build/scripts/list_versions.py kubernetes
0.4.1
0.4.2
0.4.3
0.4.4
0.5.1
0.5.2
0.5.3
0.5.4
0.5.5
0.5.6
0.6.0
0.6.1
0.6.2
0.7.0
0.7.1
0.7.2
0.7.3
0.7.4
0.8.0
0.8.1
0.8.2
0.8.4
0.9.0
0.9.1
0.9.2
0.9.3
0.10.0
0.10.1
0.11.0
0.12.0
0.12.1
0.12.2
0.13.0
0.13.1
0.13.2
0.14.0
0.14.1
0.14.2
0.15.0
0.16.0
0.16.1
0.16.2
0.17.0
0.17.1
0.18.0
0.18.1
0.18.2
0.19.0
0.19.1
0.19.2
0.19.3
0.20.0
0.20.1
0.20.2
0.21.0
0.21.1
0.21.2
0.21.3
0.21.4
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.1.0
1.1.1
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.2.7
1.3.0
1.3.1
1.3.2
1.3.3
1.3.4
1.3.5
1.3.6
1.3.7
1.3.8
1.3.9
1.3.10
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.4.5
1.4.6
$ echo $?
0
```
2. Get released versions of Kubernetes using Python3
```
$ python3 ./build/scripts/list_versions.py docker
$ python3 ./build/scripts/list_versions.py kubernetes
0.4.1
0.4.2
0.4.3
0.4.4
0.5.1
0.5.2
0.5.3
0.5.4
0.5.5
0.5.6
0.6.0
0.6.1
0.6.2
0.7.0
0.7.1
0.7.2
0.7.3
0.7.4
0.8.0
0.8.1
0.8.2
0.8.4
0.9.0
0.9.1
0.9.2
0.9.3
0.10.0
0.10.1
0.11.0
0.12.0
0.12.1
0.12.2
0.13.0
0.13.1
0.13.2
0.14.0
0.14.1
0.14.2
0.15.0
0.16.0
0.16.1
0.16.2
0.17.0
0.17.1
0.18.0
0.18.1
0.18.2
0.19.0
0.19.1
0.19.2
0.19.3
0.20.0
0.20.1
0.20.2
0.21.0
0.21.1
0.21.2
0.21.3
0.21.4
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.1.0
1.1.1
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.2.7
1.3.0
1.3.1
1.3.2
1.3.3
1.3.4
1.3.5
1.3.6
1.3.7
1.3.8
1.3.9
1.3.10
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.4.5
1.4.6
$ echo $?
0
```
3. Get released versions and latest release candidate of Kubernetes using Python2
```
$ python2 ./build/scripts/list_versions.py --include-rc kubernetes
0.4.1
0.4.2
0.4.3
0.4.4
0.5.1
0.5.2
0.5.3
0.5.4
0.5.5
0.5.6
0.6.0
0.6.1
0.6.2
0.7.0
0.7.1
0.7.2
0.7.3
0.7.4
0.8.0
0.8.1
0.8.2
0.8.4
0.9.0
0.9.1
0.9.2
0.9.3
0.10.0
0.10.1
0.11.0
0.12.0
0.12.1
0.12.2
0.13.0
0.13.1
0.13.2
0.14.0
0.14.1
0.14.2
0.15.0
0.16.0
0.16.1
0.16.2
0.17.0
0.17.1
0.18.0
0.18.1
0.18.2
0.19.0
0.19.1
0.19.2
0.19.3
0.20.0
0.20.1
0.20.2
0.21.0
0.21.1
0.21.2
0.21.3
0.21.4
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.1.0
1.1.1
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.2.7
1.3.0
1.3.1
1.3.2
1.3.3
1.3.4
1.3.5
1.3.6
1.3.7
1.3.8
1.3.9
1.3.10
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.4.5
1.4.6
1.5.0-beta.1
$ echo $?
0
```
4. Get released versions and latest release candidate of Kubernetes using Python3
```
$ python3 ./build/scripts/list_versions.py --include-rc kubernetes
0.4.1
0.4.2
0.4.3
0.4.4
0.5.1
0.5.2
0.5.3
0.5.4
0.5.5
0.5.6
0.6.0
0.6.1
0.6.2
0.7.0
0.7.1
0.7.2
0.7.3
0.7.4
0.8.0
0.8.1
0.8.2
0.8.4
0.9.0
0.9.1
0.9.2
0.9.3
0.10.0
0.10.1
0.11.0
0.12.0
0.12.1
0.12.2
0.13.0
0.13.1
0.13.2
0.14.0
0.14.1
0.14.2
0.15.0
0.16.0
0.16.1
0.16.2
0.17.0
0.17.1
0.18.0
0.18.1
0.18.2
0.19.0
0.19.1
0.19.2
0.19.3
0.20.0
0.20.1
0.20.2
0.21.0
0.21.1
0.21.2
0.21.3
0.21.4
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.1.0
1.1.1
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.2.7
1.3.0
1.3.1
1.3.2
1.3.3
1.3.4
1.3.5
1.3.6
1.3.7
1.3.8
1.3.9
1.3.10
1.4.0
1.4.1
1.4.2
1.4.3
1.4.4
1.4.5
1.4.6
1.5.0-beta.1
$ echo $?
0
```

**Comment by marccarre** [comment]
1. Error: no argument passed
```
$ python2 ./build/scripts/list_versions.py
ERROR: Please provide a dependency to get versions of. Expected 1 argument but got 0: [].
Usage:
    list_versions.py [OPTION]... [DEPENDENCY]
Examples:
    list_versions.py docker
    list_versions.py --include-rc docker
Options:
--include-rc    Include latest release candidate version.
-h/--help       Prints this!
$ echo $?
2
```
2. Error: invalid argument passed
```
$ python2 ./build/scripts/list_versions.py invalid_dependency
ERROR: Please provide a valid dependency. Supported one dependency among {go, docker, kubernetes} but got: invalid_dependency.
Usage:
    list_versions.py [OPTION]... [DEPENDENCY]
Examples:
    list_versions.py docker
    list_versions.py --include-rc docker
Options:
--include-rc    Include latest release candidate version.
-h/--help       Prints this!
$ echo $?
2
```
3. Error: invalid option passed
```
$ python2 ./build/scripts/list_versions.py --invalid_option docker
ERROR: option --invalid_option not recognized
Usage:
    list_versions.py [OPTION]... [DEPENDENCY]
Examples:
    list_versions.py docker
    list_versions.py --include-rc docker
Options:
--include-rc    Include latest release candidate version.
-h/--help       Prints this!
$ echo $?
2

```
4. Other errors:
`1` is used as the status code for other runtime errors.
5. Print help (short)
```
$ python2 ./build/scripts/list_versions.py -h
Usage:
    list_versions.py [OPTION]... [DEPENDENCY]
Examples:
    list_versions.py docker
    list_versions.py --include-rc docker
Options:
--include-rc    Include latest release candidate version.
-h/--help       Prints this!
$ echo $?
0
```
6. Print help (long)
```
$ python2 ./build/scripts/list_versions.py --help
Usage:
    list_versions.py [OPTION]... [DEPENDENCY]
Examples:
    list_versions.py docker
    list_versions.py --include-rc docker
Options:
--include-rc    Include latest release candidate version.
-h/--help       Prints this!
$ echo $?
0
```

**Comment by marccarre** [comment]
@awh / @bboreham / @brb, is there any "minimum supported version" for:
* Go?
* Kubernetes?

For Docker, as discussed with @awh, I have set the minimum to be `1.6.0`.

**Comment by bboreham** [comment]
weave-kube needs minimum Kubernetes 1.4.0

I can't think why we would want to support Go versions before 1.7.3, given that's what we use in the build container.

**Comment by marccarre** [comment]
Closing as this should probably go to [build-tools](https://github.com/weaveworks/build-tools), ultimately pulled under `weave/tools` as a git submodule.

**Pull request closed without merging**
