### PR TITLE
Update README to use new single `weave launch` command

### PR DESCRIPTION
**Pull request by awh**
Defer merge until #962 is released.

### CODE REVIEW

**Comment by rade** [comment]
I'd like to go a bit further here, if possible, and excise any mention of weaveDNS or the proxy from the README. On that note, I have been wondering whether we should rename `weave proxy-[env|config]` to just `weave env|config`.

**Comment by rade** [comment]
This PR can become a collector for all the README changes that need to be merged at release time. I suggest we put the branch into the main repo, so its easier for everybody to work on it.

**Comment by awh** [comment]
> excise any mention of weaveDNS or the proxy

I'll give it a go.

> On that note, I have been wondering whether we should rename weave proxy-[env|config]

Seems reasonable.

> I suggest we put the branch into the main repo, so its easier for everybody to work on it.

Good idea. I'll have to close this PR and make a new one.

**Comment by rade** [comment]
I have raised #1014 for `weave env|config`.

**Pull request closed without merging**
