### PR TITLE
Update tests to run against Kubernetes 1.10

### PR DESCRIPTION
**Pull request by bboreham**
Had to fix up one place where it compares `1.6` against `1.10` and gets the wrong answer.

### CODE REVIEW

**Comment by brb** [comment]
Shall we change the base to 2.2?

**Comment by bboreham** [comment]
I was thinking we can’t run the build on the 2.2 branch any more because of the package issues. But maybe it would use a cached build container?

**Comment by brb** [comment]
Building on the 2.2 seems to be working: https://circleci.com/gh/weaveworks/weave/10164

**Comment by bboreham** [comment]
I changed the base to 2.2

**Comment by bboreham** [comment]
and the build failed

**Pull request merged**
