### PR TITLE
Allow the log level of the v2 plugin to be configured

### PR DESCRIPTION
**Pull request by lalinsky**

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the contribution!

I'm just running the full CI suite.

**Comment by brb** [comment]
You probably want to add `WEAVE_LOG_LEVEL` to https://github.com/weaveworks/weave/blob/master/prog/net-plugin/config.json#L52 to make the param configurable via `docker plugin set <..>`.

**Comment by lalinsky** [comment]
Hm, now I'm not sure if it's a good idea to do this. I will add it, but perhaps the Docker plugin configuration file shouldn't be overloaded with variables like this?

Btw, was it intentionally set to debug level?

**Comment by brb** [comment]
> Hm, now I'm not sure if it's a good idea to do this. I will add it, but perhaps the Docker plugin configuration file shouldn't be overloaded with variables like this?

Maybe I'm missing something, but how would you configure the log level param if it hasn't been exposed as a Docker plugin param?

> Btw, was it intentionally set to debug level?

The plugin is quite new, so just for easier debugging of user problems.

**Comment by bboreham** [comment]
Another version has been proposed: #3197 - did you have a specific reason for closing this one @lalinsky ?

**Pull request closed without merging**
