### PR TITLE
Improve proxy restart reattach test reliability

### LINKED ISSUE #1588: (spurious?) failures in 640_proxy_restart_reattaches_test
https://circleci.com/gh/weaveworks/weave/3387
https://circleci.com/gh/weaveworks/weave/3378
https://circleci.com/gh/weaveworks/weave/3375

### PR DESCRIPTION
**Pull request by awh**
Improves some symptoms discussed at #1588 and test hanging caused by #1556.  
Note this PR does not fix the root cause of either.

### CODE REVIEW

**Comment by bboreham** [comment]
Having run this a few times, I see random cases where Docker fails to restart weave or weaveproxy, sometimes with an error like

    Error leaving endpoint id 6477a3ef6dbcce772b4e1d8a59fdb933c68e0ab0c7a897fa52520456bc650b24 for container 709d2fe08dd4cceeec6f607a80d124000402eff283a19d28543f13c57bcdeec1: no container is attached to the endpoint

and sometimes just `Killed`.

So maybe the underlying mechanism has some unreliability that we cannot get past?

**Comment by awh** [comment]
I noticed this a number of times with the router whilst developing this PR - `docker logs weave` looked like this each time after the tests had restarted the docker daemon:

```
INFO: 2015/11/03 12:03:08.703305 === received SIGINT/SIGTERM ===
*** exiting
invalid argument
```

**Comment by awh** [comment]
> and test hanging caused by #1556.

Note that this PR *doesn't* fix #1556 itself - it just prevents the test from blocking forever if it eventuates.

**Comment by awh** [comment]
> So maybe the underlying mechanism has some unreliability that we cannot get past?

Could [this](https://github.com/docker/docker/issues/17577) be the culprit? "The error is triggered by trying to run concurrent --net=host containers" - in our situation the daemon is trying to restart the router and proxy, both of which use `--net=host`

**Comment by bboreham** [comment]
Running this a few more times to try to generate failures; seeing this in Docker debug logging:

````
Nov  4 15:34:24 host1 docker[27173]: time="2015-11-04T15:34:24.319744082Z" level=warning msg="exit status 1"
Nov  4 15:34:24 host1 docker[27173]: time="2015-11-04T15:34:24.348606618Z" level=debug msg="Put on a non-mounted device baa77aff6db49a8b535cc1a4c04c0bb2bd0be6c58f2aa65576e536d4a2a77b18"
Nov  4 15:34:24 host1 docker[27173]: time="2015-11-04T15:34:24.353992746Z" level=debug msg="Failed to unmount baa77aff6db49a8b535cc1a4c04c0bb2bd0be6c58f2aa65576e536d4a2a77b18 overlay: invalid argument"
Nov  4 15:34:24 host1 docker[27173]: time="2015-11-04T15:34:24.354223405Z" level=debug msg="Failed to start container baa77aff6db49a8b535cc1a4c04c0bb2bd0be6c58f2aa65576e536d4a2a77b18: [8] System error: invalid argument"
````

Similar-sounding reports at https://github.com/docker/docker/issues/17118 and https://github.com/docker/docker/issues/17611

**Pull request merged**
