### PR TITLE
Add GET /ip handler to return all IPAM mappings.

### PR DESCRIPTION
**Pull request by tomwilkie**
Scope needs to know the IP addresses of containers.

### CODE REVIEW

**Comment by rade** [comment]
> Scope needs to know the IP addresses of containers.

...but what you have implemented only returns the automatically allocated addresses.

What's wrong with `weave ps`?

**Comment by tomwilkie** [comment]
I don't want to repeatedly invoke a shell script; the idea would be for IPAM to also record the IP addresses of non-allocated containers.  Its already told about them by the weave script and the proxy, so 'all' thats needed is for IPAM to not ignore the requests, as it does in https://github.com/weaveworks/weave/blob/master/ipam/claim.go#L34

What do you think?

**Comment by rade** [comment]
>  the idea would be for IPAM to also record the IP addresses of non-allocated containers.

IPAM should not get involved in anything outside its range. Introduces an artificial coupling.

> I don't want to repeatedly invoke a shell script

That doesn't strike me as all that bad.

**Comment by squaremo** [comment]
> I don't want to repeatedly invoke a shell script
> 
> That doesn't strike me as all that bad.

NB in the case of e.g., the docker plugin, the interfaces are not named (exactly) `"ethwe"`; i.e., `weave ps` assumes interfaces are assigned by the weave script. It might be a reasonable assumption for the minute, but probably won't remain so.

**Comment by tomwilkie** [comment]
Using the output of ```weave ps``` was a pain.  Had to include the weave script and the docker cli in the scope image.  And have to parse the output of the script.  Yuk.

https://github.com/weaveworks/scope/pull/386

**Comment by rade** [comment]
> Using the output of weave ps was a pain

doesn't look all that painful.

>  Had to include the weave script and the docker cli in the scope image

That is somewhat annoying, but otoh it means you can now also invoke any other `weave` commands.

Can we close this?

**Comment by bboreham** [comment]
I need a function like this for debugging, reasonably often.

**Pull request merged**
