### PR TITLE
Add an iptables rule for letting weaveDNS requests in

### LINKED ISSUE #1578: DNS broken on Ubuntu 15.10 desktop (w UFW)
When running Weave on Ubuntu:

```
$ ./weave launch
$ C2=$(./weave run --name c1 -ti ubuntu  /bin/bash)
$ C2=$(./weave run --name c2 -ti ubuntu  /bin/bash)
$ docker attach $C2
# ping c1
ping: unknown host c1
```

The container can `ping` the DNS resolver:

```
# cat /etc/resolv.conf 
nameserver 172.17.42.1
# ping 172.17.42.1
PING 172.17.42.1 (172.17.42.1) 56(84) bytes of data.
64 bytes from 172.17.42.1: icmp_seq=1 ttl=64 time=0.043 ms
64 bytes from 172.17.42.1: icmp_seq=2 ttl=64 time=0.043 ms
64 bytes from 172.17.42.1: icmp_seq=3 ttl=64 time=0.059 ms
64 bytes from 172.17.42.1: icmp_seq=4 ttl=64 time=0.059 ms
...
```

But `ufw` seems to be blocking traffic to the DNS server:

```
$ sudo tcpdump -n -i docker0    "port 53"
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on docker0, link-type EN10MB (Ethernet), capture size 262144 bytes
12:59:08.381052 IP 172.17.0.2.48960 > 172.17.42.1.53: 56666+ A? c1.weave.local. (32)
12:59:13.381821 IP 172.17.0.2.48960 > 172.17.42.1.53: 56666+ A? c1.weave.local. (32)
12:59:18.383369 IP 172.17.0.2.37360 > 172.17.42.1.53: 30668+ A? c1. (20)
12:59:23.388212 IP 172.17.0.2.37360 > 172.17.42.1.53: 30668+ A? c1. (20)
```

It can be seen with

```
$ dmesg 
[ 3029.623661] [UFW BLOCK] IN=docker0 OUT= PHYSIN=vethf203be5 MAC=02:42:b6:97:66:4f:02:42:ac:11:00:02:08:00 SRC=172.17.0.2 DST=172.17.42.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=52288 DF PROTO=UDP SPT=54743 DPT=53 LEN=40 
```

### PR DESCRIPTION
**Pull request by inercia**
Fixes #1578

(continued from #1581)

### CODE REVIEW

**Comment by rade** [comment]
There are a couple of bugs:

1. the rules should also be added when attaching a router, i.e. really the addition should happen in `attach_router`. That also means it should be triggered on `-z "$NO_DNS_OPT"`, since `$DNS_PORT_MAPPING` is not always available in `attach_router`.
2. the rules should be removed on `weave reset`

An alternative would be to install the rules in `create_bridge` and remove them in `destroy_bridge`. That has the advantage of keeping all the iptabling (except for `expose`) in one place. The disadvantage is that the rule may not be necessary.

**Comment by awh** [comment]
> An alternative would be to install the rules in create_bridge and remove them in destroy_bridge.

+1

**Comment by inercia** [comment]
Issue  #1631 is also affected by this: pot 6784 is not open for connections coming from other containers. Should I also open this port? Any other ports?

**Comment by rade** [comment]
> port 6784 is not open for connections coming from other containers. Should I also open this port? 

That would be a spectacularly bad idea. See #1632.

**Comment by inercia** [comment]
> That would be a spectacularly bad idea. See #1632.

:joy: ok, I'll take that as a no...

**Comment by awh** [comment]
@inercia Has this been accidentally rebased on `master`? There are 19 commits showing in this PR that look like they come from there...

**Comment by inercia** [comment]
> @inercia Has this been accidentally rebased on master? There are 19 commits showing in this PR that look like they come from there...

Damn! Fixing it...

**Pull request merged**
