### PR TITLE
Fix iptable rules generated for Ingress NetworkPolicy when both port and IP block specified

### PR DESCRIPTION
**Pull request by kitt1987**
Fix https://github.com/weaveworks/weave/issues/3653

### CODE REVIEW

**Comment by murali-reddy** [comment]
@kitt1987 thanks for the PR.

Since CI can not run from the branches on forked repo I pushed your branch to weave repo. CI seems to be failing in an unrelated test but what seems to be result of new test in this PR. Can you please add cleanup logic end of the test to delete pod and network policy?

**Comment by kitt1987** [comment]
OK.
I've fixed it in the last commit.

**Comment by kitt1987** [comment]
@murali-reddy
Could you plz help run the CI again? I don't know exactly why the netlify failed.

**Comment by murali-reddy** [comment]
I rerun the test. For some reason `602_proxy_docker_py_test.sh` continues to fail. I will check again and revert back.

**Comment by kitt1987** [comment]
Thanks

**Comment by KresoDenis** [comment]
Will this get into next release.

**Comment by bboreham** [comment]
CI ran successfully at https://circleci.com/workflow-run/d066cfca-f297-4b11-86a3-0339a5424e36
I experimented with rebasing this against the 2.5 branch, but the unit test relies on other changes not on that branch.

**Pull request merged**
