### PR TITLE
'weave --local create-bridge' is not compatible with fastdp

### PR DESCRIPTION
**Pull request by dpw**
Addresses #1552.

### CODE REVIEW

**Comment by rade** [comment]
Hmm. So `weave create-bridge` doesn't do something useful even when docker *is* running?

**Comment by dpw** [comment]
Whether `weave create-bridge` does something useful is questionable.  It creates something, but it's not a normal bridge, and you can't do anything with it that doesn't involve further weave commands that would do `create_bridge` anyway.  So I can't think of a reason why someone would do `weave create-bridge` rather than `weave create-bridge --local`.  Can you?

**Comment by rade** [comment]
>  I can't think of a reason why someone would do `weave create-bridge` rather than `weave create-bridge --local`.  Can you?

I can't. Though perhaps the comment stating "create-bridge is run without the docker daemon" could do with some rephrasing, since create-bridge may be run *with* the docker daemon.

**Comment by awh** [comment]
@dpw would you like to reword the comment before I merge?

**Comment by dpw** [comment]
Done

**Pull request merged**
