### PR TITLE
Fix documentation's formatting.

### PR DESCRIPTION
**Pull request by marccarre**
Attempt to fix the formatting of [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

### CODE REVIEW

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by awh** [comment]
#### Documentation changes:
modified [kube-addon](https://dev-weavewww.pantheonsite.io/docs/net/fix-doc-formatting/kube-addon/)

**Comment by marccarre** [comment]
cc @abuehrle

**Pull request merged**
