### PR TITLE
Move plugin arguments from separate doc into main plugin doc

### LINKED ISSUE #2243: Docs say plugin can be launched with "--mesh-network-name", plugin says otherwise
From https://www.weave.works/documentation/net-1.5.0-plugin/net-1.5.0-plug-in-command-line/:

> --mesh-network-name=<name> — set <name> to blank to disable creation of a default network, or include a name of your own choice.

From reality:

```
Toms-MacBook-Pro:scope twilkie$ weave launch-plugin --log-level=debug --mesh-network-name=
...
Status: Downloaded newer image for weaveworks/plugin:1.5.0
66d7c3400e0ebf43b8be3f5d63f095312d356ce7178be61fcc5600ba1399072e
The weaveplugin container has died. Consult the container logs for further details.
Toms-MacBook-Pro:scope twilkie$ docker logs weaveplugin
flag provided but not defined: -mesh-network-name
Usage of /home/weave/plugin:
  -cni-ipam
    	act as a CNI IPAM plugin
  -cni-net
    	act as a CNI network plugin
  -log-level string
    	logging level (debug, info, warning, error) (default "info")
  -meshsocket string
    	socket on which to listen in mesh mode (default "/run/docker/plugins/weavemesh.sock")
  -no-multicast-route
    	do not add a multicast route to network endpoints
  -socket string
    	socket on which to listen (default "/run/docker/plugins/weave.sock")
  -version
    	print version and exit
```

### PR DESCRIPTION
**Pull request by bboreham**
and add table of contents with sub-heading anchors

Fixes #2243

cc @abuehrle

### CODE REVIEW

**Comment by abuehrle** [comment]
LGTM

**Comment by awh** [comment]
modified site/plugin.md

**Comment by awh** [comment]
modified site/plugin.md removed site/plugin/plug-in-command-line.md

**Comment by awh** [comment]
```
modified site/plugin.md removed site/plugin/plug-in-command-line.md
```

**Comment by awh** [comment]
modified site/plugin.md removed site/plugin/plug-in-command-line.md

**Comment by awh** [comment]
modified site/plugin.md removed site/plugin/plug-in-command-line.md<br/>

**Comment by awh** [comment]
modified site/plugin.md<br/>
removed site/plugin/plug-in-command-line.md<br/>

**Comment by awh** [comment]
modified http://wordpress.local/site/plugin/
removed http://wordpress.local/site/plugin/plug-in-command-line/

**Comment by awh** [comment]
removed http://wordpress.local/site/plugin/plug-in-command-line/
modified http://wordpress.local/site/plugin/

**Comment by awh** [comment]
### Documentation changes:
modified http://wordpress.local/site/plugin/
removed http://wordpress.local/site/plugin/plug-in-command-line/

**Comment by awh** [comment]
*Documentation changes:*
modified http://wordpress.local/site/plugin/
removed http://wordpress.local/site/plugin/plug-in-command-line/

**Comment by awh** [comment]
**Documentation changes:**
modified http://wordpress.local/site/plugin/
removed http://wordpress.local/site/plugin/plug-in-command-line/

**Comment by awh** [comment]
#### Documentation changes:
modified http://wordpress.local/site/plugin/
removed http://wordpress.local/site/plugin/plug-in-command-line/

**Pull request merged**
