### PR TITLE
Try other peers for space if we get errors

### LINKED ISSUE #896: Long delay if ipam asks an absent host for space; can break launch-dns
When one allocator needs more space, it picks another peer at random to ask for space.  If it picks one that is no longer in the network then the message will be dropped; it will be retried when something else happens, but that may be 30 seconds later, on a timer-driven gossip update.

If the program that needs an IP address has a time-out shorter than 30 seconds, as weaveDNS does, then this will inevitably lead to failure.

A basic mitigation would be to pick a different peer if the chosen target is not even in the peer topology, but fixing this may require some crossing of layer abstractions.

### PR DESCRIPTION
**Pull request by bboreham**
Replacing #1005 which was against master not 1.0

Note I have done it a slow and stupid way in one commit, then improved the algorithmic complexity using a CDF and binary search in the next commit.

Fixes #896

### CODE REVIEW

**Comment by rade** [comment]
https://github.com/weaveworks/weave/pull/1005#discussion_r33182574 still needs addressing

**Comment by bboreham** [comment]
`sort.Search` is a binary search.
The algorithm implemented seems to me to be the same as the one you linked to.

**Comment by rade** [comment]
`sort.Search` requires the slice to be sorted. That is the case initially but not after the first iteration, since you subtract from the value of all entries in the tail.

>  The algorithm implemented seems to me to be the same as the one you linked to.

No, it's not. The 2nd answer says "One way to shuffle a list is to assign random numbers to each element in the list and sort by those numbers. We can extend that idea, we just have to pick weighted random numbers."

**Comment by rade** [comment]
My bad, it's the *first* answer I was referring to.

**Comment by bboreham** [comment]
You seem to be quoting the first answer; http://programmers.stackexchange.com/a/233552/124690.  Which, as noted in the comments and at the top of the answer, gives the wrong result.

**Comment by rade** [comment]
> Which, as noted in the comments and at the top of the answer, gives the wrong result.

Hence I said "It's not perfect, but perhaps good enough?"

**Comment by bboreham** [comment]
I have implemented the scheme suggested by that StackOverflow answer.  It's a bit longer in Go than in Python...

**Comment by rade** [comment]
I put some comments in https://github.com/bboreham/weave/commit/b9a069a62c04170d0f4a31a7e6fd49b79fc701cb

**Comment by rade** [comment]
I've merged this, but now 1.0 won't merge cleanly into master. @bboreham please do that merge and resolve the conflict.

**Comment by rade** [comment]
> now 1.0 won't merge cleanly into master

[fixed](https://github.com/weaveworks/weave/commit/ee2a66323e18b9e89c61dbed10973fd31dcdd796)

**Pull request merged**
