### PR TITLE
Add a switch for running AWSVPC tests

### PR DESCRIPTION
**Pull request by brb**
Adding `CLOUD_ENV: aws` to `machine.environment` in circle.yml starts tests on AWS. In addition, it enables the AWSVPC tests.

### CODE REVIEW

**Comment by bboreham** [comment]
How would someone make use of this?  Create a branch and add that `machine.environment` line?

**Comment by brb** [comment]
Yep, or use [parametrized builds](https://circleci.com/docs/nightly-builds/). Unfortunately, the latter is supported only via REST API.

**Comment by brb** [comment]
Unfortunately, the easy switch does not work, because for AWS, `parallel` has to be set to `false` (otherwise, a concurrent builder overrides `weavenetci-keys`) and it seems that in CircleCI it is not possible to control the variable thus it is hardcoded.

To address the issue, we could reuse the same instance of `weavenetci-keys` as it is done for GCE.

**Comment by bboreham** [comment]
`aws.sh` is roughly parallel to `gce.sh`; should the common parts be hoisted out to another file?  E.g. the function `vm_names` appears to be the same in each.

(There is a TODO comment speaking about DRY, but the code in that area does seem to be different between aws and gce.  At minimum the TODO should be removed)

**Comment by brb** [comment]
re moving the common parts: I'd suggest to keep it as it is for a moment while https://github.com/weaveworks/weave/pull/1895 is open.

**Comment by brb** [comment]
This can be closed after merging https://github.com/weaveworks/weave/pull/2694 and cherry-picking `test/900_awsvpc_3_test.sh`.

**Comment by brb** [comment]
Closing this PR, as the AWS provisioning part is no longer required. The 900 integration test can be cherry-picked in the future if someone decides to run the integration tests on AWS.

**Pull request closed without merging**
