### PR TITLE
Document ECS integration

### PR DESCRIPTION
**Pull request by 2opremio**
The intention is to use this as the single authoritative source of ECS AMIs, which right now are scattered around making them difficult to maintain.

@abuehrle Please review

### CODE REVIEW

**Comment by abuehrle** [comment]
Minor edits: not sure if 'out of the box' is totally correct, since software no longer ships in a box :)  but I like it, as it's kind of retro. 
-----
So that Weave Net, Weave Run and Weave Scope can be used 'out of the box', we provide a set of AMIs that are fully compatible with ECS-Optimized Amazon Linux AMIs.

The following are the latest supported Weave AMIs for each region:

**Comment by 2opremio** [comment]
Thanks @abuehrle . I included your edits and a final line linking to the ECS guide.

**Comment by rade** [comment]
Is 'Features' really the best place for this? Would have thought that https://github.com/weaveworks/weave#installation is a better place.

**Comment by 2opremio** [comment]
@rade The thing is that the AMIs also include Scope so I am not sure if it makes sense to put them in the weave-specific installation instructions. Although, arguably, the weave-specific features page doesn't make sense either.

How about leaving it in the features section and linking that from the Scope/Weave Installation section of the READMEs?

**Comment by squaremo** [comment]
`curl -D - http://docs.weave.works/weave/master/features.html` -> 404

**Comment by 2opremio** [comment]
@squaremo I will remove the link in the README and create a separate pull request with the correct link to http://docs.weave.works/weave/master/commit_id/features.html once we merge this.

This is because  http://docs.weave.works/weave/latest_release/features.html cannot be used (this docs haven't been released and we cannot use and we cannot know the commit_id before it gets merged.

**Comment by squaremo** [comment]
> This is because http://docs.weave.works/weave/latest_release/features.html cannot be used since these docs haven't been released and we cannot know the master commit_id before it gets merged.

That indicates to me that it's the wrong place to put that information (surely it will get updated on a schedule independent of weave releases?)

**Comment by 2opremio** [comment]
Yep, I think you are right @squaremo It should probably live with the other ECS stuffin guides/ (which at some point should have its own repository). I will add a markdown file there and modify this PR to link to it.

**Comment by 2opremio** [comment]
@squaremo I've updated the link in the README which the only remaining change.

**Comment by 2opremio** [comment]
Now https://github.com/weaveworks/guides/blob/master/aws-ecs/LATESTAMIs.md is the single source of truth for the latest ECS AMIs

**Pull request merged**
