### PR TITLE
Change import location for mesh

### PR DESCRIPTION
**Pull request by peterbourgon**
Mesh has moved to github.com/weaveworks/mesh, so we update the import location and remove the old code. Addresses #1889.

### CODE REVIEW

**Comment by awh** [comment]
Looks good, but needs rebase and the relevant submodule added (we removed the `go get` from the makefile, so this does not build when merged to master)

**Comment by peterbourgon** [comment]
Yes, I'm sorry I didn't make the WIP prefix; I know there's still some work to do here. Thanks!

**Comment by awh** [comment]
Looks good, but I'd like to double check that nothing has changed in `mesh/` since you created https://github.com/weaveworks/mesh before I merge it. Do you happen to know which weave repo commit you copied from?

**Comment by awh** [comment]
> Do you happen to know which weave repo commit you copied from?

Never mind, `diff` to the rescue :)

**Pull request merged**
