### PR TITLE
Handle cancelled allocation in 'weave attach'

### LINKED ISSUE #1418: mangled error when `weave attach` is cancelled
```
$ weave launch --init-peer-count=2
$ eval $(weave env)
$ docker run -ti ubuntu
^CError response from daemon: invalid CIDR address: Allocate
```

Instrumenting the proxy's `weave attach` invocation yields

```
...
+ curl --connect-timeout 3 -s -S -X POST http://172.17.0.10:6784/ip/db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab?check-alive=true
+ IPAM_CIDRS=Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled
+ [ Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled = 404 page not found ]
+ ALL_CIDRS=Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled
+ [ 0 -gt 0 ]
+ [ -n 1 ]
+ command_exists weavehosts
+ command -v weavehosts
+ docker inspect -f {{.HostsPath}} {{.Config.Hostname}} db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab
+ PATH_AND_NAME=/var/lib/docker/containers/db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab/hosts db1bb81e6866
+ weavehosts /var/lib/docker/containers/db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab/hosts db1bb81e6866 Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled
```

i.e. the IP allocation request returns a message which we subsequently attempt to parse as a CIDR.

Deduced from #1417.

### PR DESCRIPTION
**Pull request by bboreham**
Make IPAM return a simpler message and have the weave script check for that message and exit with status 0, so the proxy does not print any error message.

Fixes #1418

(replacement for #1425 which was against master not 1.1)

### CODE REVIEW

**Comment by rade** [comment]
@bboreham please take a look at my changes. If you are happy I will squash them, though squashing them into your first commit will be tricky, so may just have to squash the lot.

**Comment by bboreham** [comment]
LGTM.  I can do the squash into 2 commits - have already done it on my own branch.

**Comment by bboreham** [comment]
Squashed.

**Comment by rade** [comment]
Two issues:

1) There is an annoying blank line after the "cancelled" warning in the proxy logs:
```
INFO: 2015/09/21 19:54:47.023571 Attaching container 2f47c1e67e1b1c49e5aabbc6f0581b7ed04ada93f64c0d91f27d28cb4564bc8f with WEAVE_CIDR "" to weave network
WARN: 2015/09/21 19:54:48.690007 Attaching container 2f47c1e67e1b1c49e5aabbc6f0581b7ed04ada93f64c0d91f27d28cb4564bc8f to weave network: cancelled

INFO: 2015/09/21 19:54:48.690454 POST /v1.19/containers/2f47c1e67e1b1c49e5aabbc6f0581b7ed04ada93f64c0d91f27d28cb4564bc8f/resize?h=24&w=80
```

2) In https://github.com/weaveworks/weave/issues/1418#issuecomment-140030376 we observed that the cancellation is triggered by container death. Surely this can occur for most of the operations that invoke `ipam_cidrs`. And, furthermore, additional cancellation triggers may be introduced in the future. Yet only in `attach` do we check for the new `$IPAM_CIDRS = "cancelled"`. Elsewhere we simply carry on. And in most cases we don't even look at `$IPAM_CIDRS` at all, only `$ALL_CIDRS` (which will be empty or contain CIDRS obtained prior to cancellation). The only thing saving us here is that the subsequent operations will fail if the container has died. This seems rather fragile. Also, what happens if the container dies just before we call `ipam_cidrs`? I did a quick experiment of adding `docker kill $CONTAINER` just before the `ipam_cidrs` call in `attach`. This causes `docker run` to stall. So we get different behaviour depending on when the container died.

**Comment by bboreham** [comment]
>  I did a quick experiment of adding `docker kill $CONTAINER` just before the `ipam_cidrs` call in `attach`. 
> This causes docker run to stall.

I don't think it does, per se.  This is just the standard user-experience of weave IPAM stalling because it hasn't reached consensus.

**Comment by rade** [comment]
> This is just the standard user-experience of weave IPAM stalling because it hasn't reached consensus.

are you saying that cancelling container startup just before reaching ipam_cidrs results in a stall, but doing so during ipam_cidrs doesn't? That can't be right.

**Pull request merged**
