### PR TITLE
Template for GitHub issues

### PR DESCRIPTION
**Pull request by marccarre**
Should hopefully help triage users and diagnose bugs in more effective ways.

**Edit**:
Original sample output: https://gist.github.com/marccarre/094e1b09c9205048dd94c158f475b7e7
Current sample output below.

### CODE REVIEW

**Comment by marccarre** [comment]
Sample output:

**Comment by marccarre** [comment]
## Setup & Logs

### Weave Version
```
$ weave version
```

### Docker Version
```
$ docker version
```

### Weave Logs
```
$ docker logs weave
## or, under Kubernetes:
$ kubectl logs -n kube-system <weave-net-pod> weave
## If very long, please consider a Gist.
```

### Docker Daemon Logs
```
$ journalctl -u docker.service --no-pager
## or equivalent under your OS.
## If very long, please consider a Gist.
```

### Environment
#### Cloud provider or hardware configuration
#### OS
```
$ cat /etc/*release*
```
#### Kernel
```
$ uname -a
```
#### Network configuration:
```
$ ip route
$ ip -4 -o addr
$ iptables-save
## If very long, please consider a Gist.
```

#### Install tools
For example: `weave` script, Kubernetes daemonset YAML, KOPS, etc.

#### Misc.


## What happened?

## What you expected to happen?

## How to reproduce it? (as minimally and precisely as possible)

## Anything else we need to know?

**Comment by rade** [comment]
Why wouldn't we package most of the above into a `weave ...` command?

And why no `weave report`?

**Comment by marccarre** [comment]
> Why wouldn't we package most of the above into a weave ... command?
+1

**Comment by marccarre** [comment]
> And why no weave report?

Had it on my list and accidentally forgot it. Adding it now.

**Comment by marccarre** [comment]
+ Kubernetes version, which I had also forgotten.

**Comment by marccarre** [comment]
A) Any suggestion for the name of the command?

1. `weave bug-report`?
2. `weave gh-issue`?
3. `weave full-report`?
4. `weave full-details`?

B) Do we foresee any issue running this command (which would mean meta troubleshooting...) vs. separate commands (which would maybe mean they are more the responsibility of the end-user)?
* with `sudo` or without `sudo`?
* `--kubeconfig /etc/kubernetes/admin.conf`?
* anything else?

**Comment by rade** [comment]
Bear in mind that the more things we ask the user to do, the less likely they are actually going to file a bug report. Which would be bad.

Also, not all issues filed by users are bug reports. Some are feature requests, questions, etc, where little/none of all that info is relevant.

**Comment by marccarre** [comment]
> Bear in mind that the more things we ask the user to do, the less likely they are actually going to file a bug report. Which would be bad.

Yes, that's exactly what I thought when you mentioned having a single command to run.

> Also, not all issues filed by users are bug reports. Some are feature requests, questions, etc, where little/none of all that info is relevant.

That's covered by the comments you see when you click on "New Issue", but which aren't rendered in the above sample output. See actual diff.

**Comment by marccarre** [comment]
@rade, just to clarify my intent behind this PR:
1. I'd like to help users engage us in the best possible way (e.g. the `Is this a REQUEST FOR HELP?` section suggests useful resources and points to the help page where we mention Slack)
2. in case of a bug, I wanted to **suggest** a template (people do not have to follow it necessarily and can edit at will!) for end-users so they provide as much relevant information as possible up-front, as I've seen a lot of back and forth to get basic information/logs/etc. in the past (e.g. 12 days to know the exact Docker package on this issue: https://github.com/weaveworks/weave/issues/2835#issuecomment-288132014), which in the end is bad for everyone: 
    - end-users don't receive timely help
    - we miss opportunities to help them be successful with Weave Net, to fix bugs, etc.
3. also, in quite a few cases we've had replies like "*sorry, I've already removed the cluster*", while providing guidance up-front could have avoided this.
4. it is common practice to have such template, e.g.:
    - https://github.com/kubernetes/kubernetes/issues/new
    - https://github.com/hashicorp/terraform/issues/new

I'm all for making this less manual with an unique command, and even ultimately fully automate it, but in the meantime, I believe this PR is a small step forward.
Please let me know if you're completely against it, and I'll just close the PR. Thanks!

**Comment by rade** [comment]
I am not against this, but feel the list of stuff we ask for is simply too long. Note that the examples you cite ask for considerably less info.

I fear as it stands the first impression to potential bug submitters will be "This is daunting, I don't have time for this."

So until we have packaged things into a command, we should ask for less.

**Comment by marccarre** [comment]
I have rephrased a few things and shortened it a bit for now.
I may come up with a command later, but any issue running it may create even more confusion among users. 

As usual, any constructive feedback is welcome! @brb, @bboreham feel free to share your opinion!

Note that text within HTML comment blocks (`<!-- -->`) does not get rendered by Markdown, but they appear when you click the "New Issue" button.

------
```
<!--
Hi, thank you for opening an issue!
Before hitting the button...

** Is this a REQUEST FOR HELP? **
If so, please have a look at:
- our FAQ: https://www.weave.works/docs/net/latest/faq/
- our troubleshooting page: https://www.weave.works/docs/net/latest/troubleshooting/
- our help page, to choose the best channel (Slack, etc.) to reach out: https://www.weave.works/help/

** Is this a FEATURE REQUEST? **
If so, please search existing feature requests, and if you find a similar one, up-vote it and/or add your comments to it instead.
If you did not find a similar one, please describe in details:
- why: your use-case, specific constraints you may have, etc.
- what: the feature/behaviour/change you would like to see in Weave Net
Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".

** Is this a BUG REPORT? **
If so, please search existing bug reports, and if you find a similar one, up-vote it and/or add your comments to it instead.
If you did not find a similar one, please fill in as much of the template below as you can.
If you leave out information, we will not be able to help you as well.

In all cases, be ready for follow-up questions and please respond in a timely manner.
If we cannot reproduce a bug or think a feature already exists, we might close your issue.
If we are wrong, please feel free to reopen it and explain why.

Thank you!
-->
```

## Environment:

### Weave:
```
$ weave report
```

### Docker:
```
$ docker version
$ docker-runc --version
```

### Kubernetes:
```
$ kubectl version
```

### Logs:
```
<!-- Anything interesting or unusual output by the below, potentially relevant, commands? -->
<!-- (If output is long, please consider a Gist.) -->
```
```
$ docker logs weave
$ journalctl -u docker.service --no-pager
$ kubectl logs -n kube-system <weave-net-pod> weave
$ kubectl get events
```

### OS:
```
$ uname -a
$ cat /etc/*release*
```

### Network:
```
$ ip route
$ ip -4 -o addr
```
```
<!-- Anything interesting or unusual output by iptables-save? -->
<!-- (If output is long, please consider a Gist.) -->
```

## What you expected to happen?

## What happened?
```
<!-- Error message, actual behaviour, etc. -->
```

## How to reproduce it?
```
<!-- Specific steps, as minimally and precisely as possible. -->
```

## Anything else we need to know?
```
<!-- Cloud provider? Hardware? How did you configure your cluster? Kubernetes YAML, KOPS, etc. -->
```

**Comment by marccarre** [comment]
FYI, draft of command in `full-report` branch: https://github.com/weaveworks/weave/commit/1fb5b8c95e55cc6d8569ad697c59192cdc5253d8
I can already see plenty of ways this could go wrong, so not sure I want to continue in this direction.

**Comment by bboreham** [comment]
I think `weave report` is way too detailed to be included like this.
Also we don't want people adding "I have this issue too" to _similar_ bug reports; mostly they are not the same and it gets very difficult to follow the threads.

I made some edits and uploaded in branch gh-issue-template-bryan
see https://raw.githubusercontent.com/weaveworks/weave/648709b3e76e9f8b2614c88d01f4ce955222ce4c/.github/ISSUE_TEMPLATE.md

**Comment by marccarre** [comment]
@bboreham, I'd be fine having the version with your edits: this would be much better than no template at all!
Feel free to override this PR with it and I'll merge it.

**Comment by bboreham** [comment]
I pushed my version onto this branch

**Pull request merged**
