### PR TITLE
Eliminate dot imports

### PR DESCRIPTION
**Pull request by awh**
They're bad, m'kay?

cc @peterbourgon

### CODE REVIEW

**Comment by rade** [comment]
Why not a few strategically placed

    var Log = common.Log

instead?

**Comment by peterbourgon** [comment]
Why pollute the global namespace with variables and introduce an additional layer of indirection just to save a few keystrokes?

**Comment by rade** [comment]
those keystrokes you are saving are adding noise for the reader.

**Comment by peterbourgon** [comment]
They don't add noise, rather explicitness. The goal is to minimize ambiguity, not quantity of characters, and `common.Log` is strictly less ambiguous than `Log`.

**Comment by rade** [comment]
`Log` is not ambiguous. Otherwise it wouldn't compile :)

**Comment by rade** [comment]
overall, may I ask what problem we are trying to solve here?

**Comment by peterbourgon** [comment]
> Except for this one case, do not use `import .` in your programs. It makes the programs much harder to read because it is unclear whether a name like Quux is a top-level identifier in the current package or in an imported package.
—https://github.com/golang/go/wiki/CodeReviewComments#import-dot

**Comment by rade** [comment]
And has anybody actually run into this problem when reading the weave code?

**Comment by peterbourgon** [comment]
I have.

**Comment by rade** [comment]
So you read the weave code, came across a statement like

    Log.Println("Our name is", router.Ourself)

and wondered "Where does `Log` come from?". Then what happened?

**Comment by bboreham** [comment]
`common` is a poor name.

`log.Log.Infof` is more explanatory, but stutters a bit. We could repeat all the entry points in a `weave/log` package, to avoid that.

For those bits of code that are really libraries, it might be better to pass in a logger reference on startup, then the caller has control.

**Comment by awh** [comment]
I wanted to force the issue of refactoring `common` by making its use glaringly obvious - can the consequent improvements go in separate PRs?

**Comment by awh** [comment]
@bboreham is there a reason we can't just merge this now? It's a strict refactoring...

**Comment by bboreham** [comment]
Because it makes the code strictly more ugly.

**Comment by rade** [comment]
>  it makes the code strictly more ugly

I was hoping that https://github.com/weaveworks/weave/pull/2002#issuecomment-188861434 might be an acceptable compromise.

**Comment by awh** [comment]
> Because it makes the code strictly more ugly.

https://github.com/weaveworks/weave/pull/2002#issuecomment-191175405

**Comment by rade** [comment]
I have eliminated the bulk of dot imports.

The remainder will be removed with #2074.

-> closing.

**Pull request closed without merging**
