### PR TITLE
[proxy] Fully close TLS sockets, as they have no CloseWrite

### LINKED ISSUE #1182: Streaming TLS Connections are not terminated cleanly
`net.Conn` does not include the `CloseWrite()` method. We typecast, to a `CloseWriter`, but `tls.Conn` does not expose that method. Therefore, when clients do a streaming request to the proxy over TLS (e.g. when attaching to a container), their client will hang instead of terminating the connection.

### PR DESCRIPTION
**Pull request by paulbellamy**
Fixes #1182

Testing this behaviour involves either: allocating a pty for "docker run" and checking a timeout, or using a different client, so I'm not sure it's worth the time investment.

### CODE REVIEW

**Comment by paulbellamy** [comment]
@2opremio could you review this, please?

**Comment by 2opremio** [comment]
LGTM, although I would split it in two commits. One for the "sync" refactoring and another one for the actual CloseWrite change.

**Comment by rade** [comment]
This hasn't been merged from 1.0 into master yet. And there are non-trivial conflicts. Please get the merge done asap because the longer we wait the harder it gets.

**Comment by rade** [comment]
> This hasn't been merged from 1.0 into master yet. 

[done](https://github.com/weaveworks/weave/commit/dba116bae1e1a2661de40575b2461d2040963f83)

**Pull request merged**
