### PR TITLE
Connect to gce boxes as vagrant so we can access docker unix socket

### PR DESCRIPTION
**Pull request by paulbellamy**

### CODE REVIEW

**Comment by bboreham** [comment]
what is the background to this change?

**Comment by paulbellamy** [comment]
Came up while trying to write a test for https://github.com/weaveworks/weave/issues/1694

**Comment by bboreham** [comment]
So is it needed?  The tests for #1696 seem to have passed.

**Comment by paulbellamy** [comment]
#1696 included this commit.

**Comment by bboreham** [comment]
Ah, I hadn't spotted that #1696 was reverted

**Pull request merged**
