### PR TITLE
remove outermost gob

### PR DESCRIPTION
**Pull request by rade**
...replacing it with length-prefix encoding.

Addresses part of #519.

### CODE REVIEW

**Comment by dpw** [comment]
> Looks like it might end up with two identical lines in doIntroV1 and doIntroV2.

Ah, I see - they diverge again in the later commit, so no point in unifying them.

**Comment by rade** [comment]
@dpw I have addressed all your feedback. Will squash the commits once you are happy.

**Comment by dpw** [comment]
That was all, squash away.

**Comment by rade** [comment]
> squash away

Done.

**Pull request merged**
