### PR TITLE
Upgrade Vagrantfile to Ubuntu 16.04 'bento' box

### PR DESCRIPTION
**Pull request by bboreham**
We need to upgrade Ubuntu because 'wily' (15.10) is unsupported and so many packages (e.g. Docker RCs) are not released for it.

The 'ubuntu' boxes seem to be rather broken, e.g. create a user called 'ubuntu' instead of 'vagrant', so I moved to the 'bento' box.

As a bonus, we don't need to remove puppet and chef.

I needed to upgrade to Virtualbox 5.1 before it would work.

### CODE REVIEW

**Comment by brb** [comment]
Did all tests pass locally?

**Comment by bboreham** [comment]
Yes, except 840 because we don't (yet) install Kubernetes packages and 602 for some Docker-version-related reason.

**Comment by awh** [comment]
The toplevel Vagrantfile is attempting to install docker-engine=1.10.2-0~xenial but has configured the apt docker.list to point at the wily repo. Furthermore, there is no 1.10.2-0~xenial in the correct repo.

**Comment by marccarre** [comment]
FYI: also needed to upgrade `vagrant` from `1.8.1` to `1.9.1` for it to support VirtualBox `5.1`.
It was otherwise failing with the below:

    $ vagrant up
    No usable default provider could be found for your system.
    
    Vagrant relies on interactions with 3rd party systems, known as
    "providers", to provide Vagrant with resources to run development
    environments. Examples are VirtualBox, VMware, Hyper-V.
    
    The easiest solution to this message is to install VirtualBox, which
    is available for free on all major platforms.
    
    If you believe you already have a provider available, make sure it
    is properly installed and configured. You can see more details about
    why a particular provider isn't working by forcing usage with
    `vagrant up --provider=PROVIDER`, which should give you a more specific
    error message for that particular provider.

and if you pass `--provider=virtualbox`:

    $ vagrant up --provider=virtualbox
    The provider 'virtualbox' that was requested to back the machine
    'default' is reporting that it isn't usable on this system. The
    reason is shown below:
    
    Vagrant has detected that you have a version of VirtualBox installed
    that is not supported by this version of Vagrant. Please install one of
    the supported versions listed below to use Vagrant:
    
    4.0, 4.1, 4.2, 4.3, 5.0
    
    A Vagrant update may also be available that adds support for the version
    you specified. Please check www.vagrantup.com/downloads.html to download
    the latest version.

**Comment by marccarre** [comment]
This has been replicated & reworked in #2694, so I believe we should be able to close this PR.

**Comment by brb** [comment]
https://github.com/weaveworks/weave/pull/2694 got merged, so closing this PR.

**Pull request closed without merging**
