### PR TITLE
Documentation Update for Weave Net Monitoring.

### PR DESCRIPTION
**Pull request by alok87**
Weave Net monitoring can be setup using [kube-prometheus](https://github.com/coreos/kube-prometheus/pull/425).

This PR updates the Weave Net documentation for it.

Slack conversation: https://weave-community.slack.com/archives/C2ND76PAA/p1582724906028400

Weave Net kube prometheus PR: https://github.com/coreos/kube-prometheus/pull/425

### CODE REVIEW

**Comment by alok87** [comment]
@bboreham Please also review https://github.com/coreos/kube-prometheus/pull/425 when you get time and let us know if you think we should be making some changes and if we should be adding something there.

**Comment by alok87** [comment]
@bboreham Do you want me to do any more changes here?

**Comment by alok87** [comment]
@bboreham

**Comment by bboreham** [comment]
Thanks!

**Pull request merged**
