### PR TITLE
Wait until container exits in test to remove race condition

### LINKED ISSUE #1502: sporadic failure in 666_abuse_of_start_test
Have seen this on my machine...
```
test #1 "docker_on 192.168.48.13 inspect -f '{{.State.Running}} {{.State.ExitCode}} {{.HostConfig.Dns}}' c2" failed:
	expected "false 0 [172.17.42.1]"
	got "true 0 [172.17.42.1]"
```

I suspect the test is racy; the container may not have terminated yet when `inspect` is called.

### PR DESCRIPTION
**Pull request by paulbellamy**
I expect this will fix #1502

### CODE REVIEW

**Comment by bboreham** [comment]
Do you now get `You cannot attach to a stopped container, start it first` messages in the case where there wasn't a problem previously?

**Comment by paulbellamy** [comment]
Yes, but they are hidden unless the test fails.

**Comment by rade** [comment]
That's rather misleading though.

**Comment by bboreham** [comment]
I get:

````
$ ./666_abuse_of_start_test.sh 
Abuse of 'start' operation
2c16a52b2600c4c3d59414880c1bbfc07533a9c400d356d971236630e3a87991
8811c22051e3d2346bb0974be0c9c6cd2b9744159f94ff94c48d83453ccc7823
You cannot attach to a stopped container, start it first
a88ac7421149515ffa3db7d7c7af2f8a4c63fd2dc934491e31382888eb6ae314
You cannot attach to a stopped container, start it first
86b2383e480d1a580494e498c57f9fa08613da55352633a222fa58b6cf4e3065
You cannot attach to a stopped container, start it first
5c6a707a781e6e0d186b28f36f1ece107d8f787da226bbae664401636abf2c9a
all 5 tests passed in 4.433s.
````

**Comment by rade** [comment]
Fixed in ed957715

**Pull request merged**
