### PR TITLE
CNI setup fixes

### LINKED ISSUE #2394: Using Weave CNI in Mesos: "no such file or directory" error
I'm attempting to get Weave CNI working with Mesos CNI. I've stolen commands from the K8s tutorial and merged them in with a Mesos tutorial. Everything seems to be setup correctly, but when the call is made to `/opt/bin/cni/weave-net` and hence the `docker run plugin...` command, the container fails with the logs:
```
{
    "code": 100,
    "msg": "no such file or directory"
}
```

I edited the `weave-net` script to add some debug messages like so:

```
#!/bin/sh
set -x
echo "\nEnv Vars\n"
env
echo "------"
ls /etc/cni
ls /opt/cni
ls CNI_PATH
ls /var/run/docker.sock

docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -i \
 -e CNI_VERSION -e CNI_COMMAND -e CNI_CONTAINERID -e CNI_NETNS \
 -e CNI_IFNAME -e CNI_ARGS -e CNI_PATH -v /etc/cni:/etc/cni -v /opt/cni:/opt/cni \
 weaveworks/plugin:1.6.0  --cni-net -log-level debug
```

Which resulted in:

```
ubuntu@ip-10-0-0-249:~$ sudo mesos-execute --command=/bin/bash --docker_image=ubuntu:latest --master=ec2-52-49-23-223.eu-west-1.compute.amazonaws.com:5050 --name=ubuntu --networks=weave --no-shell
I0624 08:28:19.010092  6044 scheduler.cpp:187] Version: 1.0.0
I0624 08:28:19.011386  6050 scheduler.cpp:471] New master detected at master@10.0.0.217:5050
Subscribed with ID '85ab8d71-94b0-4d7e-8a43-1938a716c786-0020'
Submitted task 'ubuntu' to agent '85ab8d71-94b0-4d7e-8a43-1938a716c786-S4'
Received status update TASK_FAILED for task 'ubuntu'
  message: 'Failed to launch container: Collect failed: The CNI plugin 'weave-net' failed to attach container 6249ab71-2ba0-4f35-bbe4-385228792284 to CNI network 'weave': 
Env Vars

CNI_PATH=/opt/cni/bin
CNI_CONTAINERID=6249ab71-2ba0-4f35-bbe4-385228792284
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CNI_NETNS=/run/mesos/isolators/network/cni/6249ab71-2ba0-4f35-bbe4-385228792284/ns
CNI_IFNAME=eth0
CNI_COMMAND=ADD
PWD=/
------
net.d
bin
/var/run/docker.sock
{
    "code": 100,
    "msg": "no such file or directory"
}; Abnormal executor termination'
  source: SOURCE_AGENT
  reason: REASON_CONTAINER_LAUNCH_FAILED
```

As you can see, all of the directories appear to be present and correct.

Also, I tracked this down to an error being thrown by the containernetworking/cni code here: https://github.com/containernetworking/cni/blob/master/vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go

But I don't know what code calls that error message.

Setup below:
```
ubuntu@ip-10-0-0-69:~$ cat /etc/mesos-slave/network_cni_config_dir 
/etc/cni/net.d
ubuntu@ip-10-0-0-69:~$ cat /etc/mesos-slave/network_cni_plugins_dir 
/opt/cni/bin
ubuntu@ip-10-0-0-69:~$ cat /etc/cni/net.d/10-weave.conf
{
    "name": "weave",
    "type": "weave-net"
}
ubuntu@ip-10-0-0-69:~$ cat /opt/cni/bin/weave-net 
#!/bin/sh
docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -i \
 -e CNI_VERSION -e CNI_COMMAND -e CNI_CONTAINERID -e CNI_NETNS \
 -e CNI_IFNAME -e CNI_ARGS -e CNI_PATH -v /etc/cni:/etc/cni -v /opt/cni:/opt/cni \
 weaveworks/plugin:1.6.0  --cni-net
ubuntu@ip-10-0-0-69:~$ sudo mesos-execute --command=/bin/bash --docker_image=ubuntu:latest --master=ec2-52-49-23-223.eu-west-1.compute.amazonaws.com:5050 --name=ubuntu --networks=weave --no-shell
I0624 08:54:44.619662  5762 scheduler.cpp:187] Version: 1.0.0
I0624 08:54:44.621544  5766 scheduler.cpp:471] New master detected at master@10.0.0.217:5050
Subscribed with ID '85ab8d71-94b0-4d7e-8a43-1938a716c786-0025'
Submitted task 'ubuntu' to agent '85ab8d71-94b0-4d7e-8a43-1938a716c786-S3'
Received status update TASK_FAILED for task 'ubuntu'
  message: 'Failed to launch container: Collect failed: The CNI plugin 'weave-net' failed to attach container 0de98310-57df-4f5e-9eb3-39d9d4499e34 to CNI network 'weave': {
    "code": 100,
    "msg": "no such file or directory"
}; Abnormal executor termination'
  source: SOURCE_AGENT
  reason: REASON_CONTAINER_LAUNCH_FAILED
```

### LINKED ISSUE #2434: 'weave setup' on Docker-for-Mac 1.12.0-rc3 fails with cni mount error
`WEAVE_VERSION=latest weave setup` reports the following:

    pidster@ $ WEAVE_VERSION=latest weave setup
    docker: Error response from daemon: Mounts denied: 
    The paths /etc/cni and /opt/cni
    are not shared from OS X and do not belong to the system.
    You can configure shared paths from Docker -> Preferences...

I am on Docker For Mac 1.12.0-rc3-beta18 (build: 9996)

### LINKED ISSUE #2435: CNI setup is only run in `weave setup` not `weave launch`
This is weird; we don't advertise `weave setup` as something you *have to* run.

### PR DESCRIPTION
**Pull request by rade**
Fixes #2434
Fixes #2394
Fixes #2435

### CODE REVIEW

**Comment by rade** [comment]
I have no easy way to test this. @errordeveloper @philwinder can you build this branch and give it a whirl?

**Comment by philwinder** [comment]
@rade: Can you point me to some build instructions? I tried make, but it failed with:
```
git submodule update --init
docker run --rm -ti \
	    -v /Volumes/source/gocode/src/github.com/weaveworks/weave:/go/src/github.com/weaveworks/weave \
		-v /Volumes/source/gocode/src/github.com/weaveworks/weave/.pkg:/go/pkg \
		-e GOARCH -e GOOS -e CIRCLECI -e CIRCLE_BUILD_NUM -e CIRCLE_NODE_TOTAL -e CIRCLE_NODE_INDEX -e COVERDIR -e SLOW \
		weaveworks/weavebuild COVERAGE= WEAVE_VERSION=git-70edbad7a483 prog/weaver/weaver
make: Entering directory '/go/src/github.com/weaveworks/weave'
make: *** No rule to make target 'prog/weaver/weaver'.  Stop.
make: Leaving directory '/go/src/github.com/weaveworks/weave'
make: *** [prog/weaver/weaver] Error 2
```

**Comment by rade** [comment]
works just fine for me. @errordeveloper might know how to build weave on a Mac.

**Comment by errordeveloper** [comment]
I haven't built it on my machine for a while, but I recall that @paulbellamy did.

**Comment by errordeveloper** [comment]
@philwinder you don't have to build this, you just want to run `./weave setup`. You can probably use release version of CNI plugin with that too, if you set `WEAVE_VERSION=1.6.0`.

**Comment by errordeveloper** [comment]
I've tested this with Docker for Mac 1.12.0-rc4-beta10 and it works fine.

**Comment by rade** [comment]
> @philwinder _actually_, you don't have to build this, you just want to run `./weave setup`.

Huh? This code is on a branch; it hasn't been merged yet.

> I've tested this with Docker for Mac 1.12.0-rc4-beta10 (currently the latest) and it works fine.

*How* did you test this if you didn't build the branch?

**Comment by errordeveloper** [comment]
> _How_ did you test this if you didn't build the branch?

Ok, now that I revisit the code, I think what I've effectively tested is just the change to `exec_remote`. In my understanding, I've not tested `setup_cni`, as I believe that runs in a container. So I can confirm that this fixes #2434 for me.

**Comment by errordeveloper** [comment]
I do not think that #2394 and #2435 are in any way related to Docker for Mac, so compiling on Mac OS shouldn't be a dependency for testing this.

**Comment by awh** [comment]
@philwinder I've built this branch and pushed it to Dockerhub - could you give it a try? You need to use the weave script that's on this branch, and use it like this:

```
DOCKERHUB_USER=harrisonadamw WEAVE_VERSION=issues-2442 weave ...
```

The main thing we need is to check if the Mesos CNI issue is fixed, but if you could also confirm that `weave setup` works on DfM at the same time that would be very helpful - thanks!

**Comment by philwinder** [comment]
@awh Unless I'm doing something wrong, the cni binaries aren't being written any more. Is that intentional? If so, where are they written to?

```
sudo curl -sL https://raw.githubusercontent.com/weaveworks/weave/cni-setup-fixes/weave -o /usr/local/bin/weave
sudo chmod a+x /usr/local/bin/weave
sudo mkdir -p /opt/cni/bin
sudo mkdir -p /etc/cni/net.d
DOCKERHUB_USER=harrisonadamw WEAVE_VERSION=issues-2442 sudo weave setup
ubuntu@ip-10-0-0-163:~$ ls /opt/cni/bin/
ubuntu@ip-10-0-0-163:~$
```

**Comment by rade** [comment]
@philwinder 

> Unless I'm doing something wrong

I'm afraid you are...

> `DOCKERHUB_USER=harrisonadamw WEAVE_VERSION=issues-2442 sudo weave setup`

Those env var settings won't be passed through sudo. You want `sudo -E`.

Alas I've found a bug....

**Comment by rade** [comment]
> Alas I've found a bug...

Fixed. @awh please generate new images for @philwinder to test.

**Comment by awh** [comment]
@philwinder I've published Matthias' latest under the same tag. This should work (make sure you grab the script again though!)

```
sudo DOCKERHUB_USER=harrisonadamw WEAVE_VERSION=issues-2442 weave setup
```

Thanks!

**Comment by awh** [comment]
For posterity:
```
make UPDATE_LATEST=false DOCKERHUB_USER=harrisonadamw WEAVE_VERSION=issues-2442 PUBLISH_WEAVEDB=true all publish
```

**Comment by awh** [comment]
@philwinder ping

**Comment by philwinder** [comment]
@awh 
I think we still have an issue. Log:
```
I0811 08:22:31.783237  5813 paths.cpp:528] Trying to chown '/var/lib/mesos/slaves/3a95c9b9-ab80-4982-a237-1885839bd463-S0/frameworks/3a95c9b9-ab80-4982-a237-1885839bd463-0012/executors/accounts-db/runs/a3e927ff-a634-4a24-86b0-4d49f6aff645' to user 'root'
I0811 08:22:31.785717  5813 slave.cpp:5674] Launching executor accounts-db of framework 3a95c9b9-ab80-4982-a237-1885839bd463-0012 with resources cpus(*):0.1; mem(*):32 in work directory '/var/lib/mesos/slaves/3a95c9b9-ab80-4982-a237-1885839bd463-S0/frameworks/3a95c9b9-ab80-4982-a237-1885839bd463-0012/executors/accounts-db/runs/a3e927ff-a634-4a24-86b0-4d49f6aff645'
I0811 08:22:31.785949  5813 slave.cpp:1840] Queuing task 'accounts-db' for executor 'accounts-db' of framework 3a95c9b9-ab80-4982-a237-1885839bd463-0012
I0811 08:22:31.786003  5813 docker.cpp:1020] Skipping non-docker container
I0811 08:22:31.786214  5812 containerizer.cpp:781] Starting container 'a3e927ff-a634-4a24-86b0-4d49f6aff645' for executor 'accounts-db' of framework '3a95c9b9-ab80-4982-a237-1885839bd463-0012'
I0811 08:22:31.787103  5812 provisioner.cpp:294] Provisioning image rootfs '/var/lib/mesos/provisioner/containers/a3e927ff-a634-4a24-86b0-4d49f6aff645/backends/copy/rootfses/ab603e43-1882-43c1-8bc1-287089eb8ebf' for container a3e927ff-a634-4a24-86b0-4d49f6aff645
I0811 08:22:33.758590  5817 slave.cpp:4591] Current disk usage 9.78%. Max allowed age: 5.615127706719491days
I0811 08:22:34.693209  5814 linux_launcher.cpp:281] Cloning child process with flags = CLONE_NEWNS | CLONE_NEWUTS | CLONE_NEWNET
I0811 08:22:34.696897  5817 cni.cpp:716] Bind mounted '/proc/13614/ns/net' to '/run/mesos/isolators/network/cni/a3e927ff-a634-4a24-86b0-4d49f6aff645/ns' for container a3e927ff-a634-4a24-86b0-4d49f6aff645
E0811 08:22:35.169728  5816 slave.cpp:3976] Container 'a3e927ff-a634-4a24-86b0-4d49f6aff645' for executor 'accounts-db' of framework 3a95c9b9-ab80-4982-a237-1885839bd463-0012 failed to start: Collect failed: The CNI plugin 'weave-net' failed to attach container a3e927ff-a634-4a24-86b0-4d49f6aff645 to CNI network 'weave': {
    "code": 100,
    "msg": "no such file or directory"
}
```

The binary is:
```
ubuntu@ip-10-0-0-60:~$ cat /opt/cni/bin/weave-net
#!/bin/sh
[ -z "$CNI_NETNS" ] || EXTRA_VOLUMES="-v $(dirname $CNI_NETNS):$(dirname $CNI_NETNS)"
docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -i \
 -e CNI_VERSION -e CNI_COMMAND -e CNI_CONTAINERID -e CNI_NETNS \
 -e CNI_IFNAME -e CNI_ARGS -e CNI_PATH \
 -v /etc/cni:/etc/cni -v /opt/cni:/opt/cni  \
 harrisonadamw/plugin:issues-2442  --cni-net
```

And the conf file is:
```
ubuntu@ip-10-0-0-60:~$ cat /etc/cni/net.d/10-weave.conf
{
    "name": "weave",
    "type": "weave-net"
}
```

So I added some debug to echo the docker command and that CNI NETNS command, and an actual example echo was:
```
docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -i  -e CNI_VERSION -e CNI_COMMAND -e CNI_CONTAINERID -e CNI_NETNS  -e CNI_IFNAME -e CNI_ARGS -e CNI_PATH  -v /etc/cni:/etc/cni -v /opt/cni:/opt/cni   harrisonadamw/plugin:issues-2442  --cni-net
-v /run/mesos/isolators/network/cni/3b198e3d-5850-462c-ac9c-f22d6d53c6b5:/run/mesos/isolators/network/cni/3b198e3d-5850-462c-ac9c-f22d6d53c6b5
```

Note the lack of the usual env var format `ENV=value`. Should you not be passing `CNI_VERSION=$CNI_VERSION`?

So obviously, when I try and run the command manually:
```
ubuntu@ip-10-0-0-60:~$ docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -i  -e CNI_VERSION -e CNI_COMMAND -e CNI_CONTAINERID -e CNI_NETNS  -e CNI_IFNAME -e CNI_ARGS -e CNI_PATH  -v /etc/cni:/etc/cni -v /opt/cni:/opt/cni   harrisonadamw/plugin:issues-2442  --cni-net
{
    "code": 100,
    "msg": "required env variables missing"
}2016/08/11 08:37:04 CNI_COMMAND env variable missing
2016/08/11 08:37:04 CNI_NETNS env variable missing
2016/08/11 08:37:04 CNI_IFNAME env variable missing
2016/08/11 08:37:04 CNI_PATH env variable missing
```

This has taken me about three hours to get working. Because of all the provisioning and editing of the scripts to accommodate the custom commands. I'd really appreciate it if you could automate this test.

**Comment by rade** [comment]
> Note the lack of the usual env var format `ENV=value`. Should you not be passing `CNI_VERSION=$CNI_VERSION`?

No, that is not necessary. `-e ENV_VAR` passes the value of the env var in the current environment.

I've found the problem though. Yet another shell escaping issue :( @awh another image please

>  I'd really appreciate it if you could automate this test.

Noted; we can probably add some tests for exotic CNI_NETNS locations.

Though ultimately we do need you to test this since the objective here is to fix the problem with mesos reported by you.

**Comment by rade** [comment]
[oh great](https://circleci.com/gh/weaveworks/weave/6631)

> Message: "/var/lib/docker/overlay/95b029892c86592c39147f0e181896bb83aff12a22840f0be7d375210c6afa9c/merged/proc/10963/ns" cannot be mounted because it is located inside "/proc"

So I guess we somehow have to exclude `/proc`.

Also, I do have my doubts whether the mounts will work in the mesos case based on

> I0811 08:22:34.696897  5817 cni.cpp:716] Bind mounted '/proc/13614/ns/net' to '/run/mesos/isolators/network/cni/a3e927ff-a634-4a24-86b0-4d49f6aff645/ns' for container a3e927ff-a634-4a24-86b0-4d49f6aff645

Does this indicate that the cni script is being executed in a container that has the above mount? If so, the mount we do in the script won't work since iirc `-v` mounts from the host.

**Comment by brb** [comment]
@philwinder Could you update your terraform script (https://github.com/philwinder/mesos-terraform) that it'd include a non-broken version of the `marathon` package, because I'm getting:
```
aws_instance.mesos-master (remote-exec): Unpacking marathon (1.3.0-1.0.499.ubuntu1404) ...
aws_instance.mesos-master (remote-exec): dpkg-deb (subprocess): cannot copy archive member from '/var/cache/apt/archives/marathon_1.3.0-1.0.499.ubuntu1404_amd64.deb' to decompressor pipe: unexpected end of file or stream
aws_instance.mesos-master (remote-exec): dpkg-deb: error: subprocess paste returned error exit status 2
aws_instance.mesos-master (remote-exec): dpkg: error processing archive /var/cache/apt/archives/marathon_1.3.0-1.0.499.ubuntu1404_amd64.deb (--unpack):
aws_instance.mesos-master (remote-exec):  cannot copy extracted data for './usr/bin/marathon' to '/usr/bin/marathon.dpkg-new': unexpected end of file or stream
```

Thanks.

**Comment by philwinder** [comment]
Hey Martynas @brb, I created a workaround branch, which uses an older version:
https://github.com/philwinder/mesos-terraform/tree/marathon/1.2

**Comment by brb** [comment]
Thanks. I was able to verify the fix - it works.

In order to use the fixed version until it has been released, replace `weave setup` and `weave launch` by:
```
sudo DOCKERHUB_USER=brb0 WEAVE_VERSION=latest weave setup
sudo DOCKERHUB_USER=brb0 WEAVE_VERSION=latest weave launch --no-dns $1
```

and don't forget to remove the workaround at https://github.com/microservices-demo/microservices-demo//blob/master/deploy/mesos-cni/provisionWeaveCNI.sh.

**Pull request merged**
