### PR TITLE
introduce '-nodiscovery' option to disable automatic peer discovery

### LINKED ISSUE #847: option to disable peer discovery
In some situations users may want complete control over the weave peer topology, i.e. exactly which peers connect to which other peers, and by what addresses.

`-nodisco`.

### PR DESCRIPTION
**Pull request by rade**
Closes #847.

### CODE REVIEW

**Comment by paulbellamy** [comment]
`-nodiscovery`, please.

**Comment by rade** [comment]
I intentionally went for the 70s pun :)

**Comment by paulbellamy** [comment]
Yeah, I appreciate the pun.

**Comment by rade** [comment]
anything else?

**Comment by paulbellamy** [comment]
In the status output, we say on/off for other items, so it would be good to use that instead of enabled/disabled.

But other than that, LGTM.

**Comment by rade** [comment]
blocked on #863.

**Pull request merged**
