### PR TITLE
Print request and response json when debugging weaveproxy

### LINKED ISSUE #1515: For debugging, provide a way to see data passing in and out of weaveproxy
Sometimes, to understand what has gone wrong, we would like to see the exact json that went in and out of the proxy.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #1515 

Simply added to debug-level logging, to avoid the added complexity of a new command-line flag to turn this on.

Thanks to @tomwilkie for the implementation

### CODE REVIEW

**Comment by tomwilkie** [comment]
Worth noting not all commands use unmarshalRequestBody, so I don't think this covers everything.

**Comment by bboreham** [comment]
ok you got me - which ones don't use it?

**Comment by rade** [comment]
surely we want something in `{un}marshalResponseBody` too.

**Comment by rade** [comment]
> which ones don't use it

`NullInterceptor`, and and the no-op `Intercept{Request/Response}` of some other interceptors.

**Comment by bboreham** [comment]
Ones we don't modify don't need to be printed.

**Pull request merged**
