### PR TITLE
Warn on detection of REJECT rule in FORWARD chain

### LINKED ISSUE #1266: Weave on a single centos7 host, Containers cant resolve each other
I have a single weave host, with two containers running on it.
I started weave
`weave launch && weave launch-dns && weave launch-proxy`
 and then started the containers with docker commands, 
`docker run -d -ti -h webnode1 --name webnode1 -p 80:80 docker.io/httpd:latest`
`docker run -d -ti -h webnode2 --name webnode2 -p 8080:80 docker.io/httpd:latest`

but i am not able to ping them from one another and then the traffic to the outside world is not passed through.

`docker exec webnode1 ping -c 5 webnode2` results in unknown host webnode2
Running the latest version of weave 1.0.1, docker is also latest version.

### PR DESCRIPTION
**Pull request by awh**
Closes #1266.

### CODE REVIEW

**Comment by awh** [comment]
Suggestions for a better error message welcome...

**Comment by rade** [comment]
This should tell the user a) *exactly* what the offending rule is, b) what the likely effect is on weave.

**Comment by awh** [comment]
Message updated.

**Comment by awh** [comment]
@rade latest revision:
````
$ ./weave launch
WARNING: existing iptables rule

    '-A FORWARD -j REJECT --reject-with icmp-host-prohibited'

will block name resolution via weaveDNS - please reconfigure your firewall.
````

**Comment by alex-sherwin** [comment]
You should give an example command of removing the rule in the warning..

**Comment by joserivca** [comment]
so it was fixed? im still having the problem!

**Pull request merged**
