### PR TITLE
Move daemonset API to apps/v1

### LINKED ISSUE #3658: Update the API for DaemonSet
The extensions/v1beta1 API has been deprecated for DaemonSet. Hence, the command:

```
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

throws the error:

```
error: unable to recognise no matches for kind "DaemonSet" in version "extensions/v1beta1"
```

Please update the DaemonSet API to apps/v1.

### PR DESCRIPTION
**Pull request by Pensu**
Fixes #3658

### CODE REVIEW

**Comment by murali-reddy** [comment]
@Pensu thanks for the PR. `weave-daemonset.yaml` is for older version of Kubernetes. I opened #3674 to avoid confusion.

Since `apps/v1` is GA in 1.9 and enabled by default I think it would be appropriate to introduce weave-daemonset-k8s-1.9.yaml. Would you mind updating the PR on the similar lines to #3353?

At some point it make sense to delete weave-daemonset-k8s-1.6/1.7/1.8.yaml which are manifests for very old versions.

**Comment by Pensu** [comment]
@murali-reddy Yeah, sure, I have updated the PR. Please check and let me know if it's ok.

**Comment by bboreham** [comment]
I think you need to start from the 1.8 version not from the pre-1.6 version.

**Comment by Pensu** [comment]
> I think you need to start from the 1.8 version not from the pre-1.6 version.

@bboreham Sorry, didn't get it. I just followed the changes from #3353

**Comment by bboreham** [comment]
It looks like your new file `weave-daemonset-k8s-1.9.yaml` is based off https://github.com/weaveworks/weave/blob/master/prog/weave-kube/weave-daemonset.yaml.

It needs to be based off https://github.com/weaveworks/weave/blob/master/prog/weave-kube/weave-daemonset-k8s-1.8.yaml

For instance, that last file is 208 lines long; I'd expect yours to be about the same.

**Comment by Pensu** [comment]
@bboreham Yeah, I have updated the PR by basing the 1.9 yaml off 1.8 one.

**Comment by murali-reddy** [comment]
@Pensu Looks like you missed change to update `apiVersion` to `apps/v1` in `weave-daemonset-k8s-1.9.yaml`

**Comment by Pensu** [comment]
@murali-reddy Yeah, thanks for pointing it out. Have updated the PR.

**Comment by murali-reddy** [comment]
LGTM

**Comment by bboreham** [comment]
I've kicked off another CI build.
Note we should include the change made in #3655 in this new file too.

To show the changes:
```
$ diff -c prog/weave-kube/weave-daemonset-k8s-1.8.yaml prog/weave-kube/weave-daemonset-k8s-1.9.yaml
*** prog/weave-kube/weave-daemonset-k8s-1.8.yaml	2018-11-01 14:16:48.557796495 +0000
--- prog/weave-kube/weave-daemonset-k8s-1.9.yaml	2019-08-28 10:06:08.153119861 +0000
***************
*** 100,106 ****
        - kind: ServiceAccount
          name: weave-net
          namespace: kube-system
!   - apiVersion: extensions/v1beta1
      kind: DaemonSet
      metadata:
        name: weave-net
--- 100,106 ----
        - kind: ServiceAccount
          name: weave-net
          namespace: kube-system
!   - apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: weave-net
***************
*** 109,114 ****
--- 109,117 ----
        namespace: kube-system
      spec:
        # Wait 5 seconds to let pod connect before rolling next pod
+       selector:
+         matchLabels:
+           name: weave-net
        minReadySeconds: 5
        template:
          metadata:
```

**Comment by Pensu** [comment]
@bboreham I have added the changes from #3655. Please check.

**Comment by bboreham** [comment]
CI succeeded at https://circleci.com/gh/weaveworks/weave/12330 - thanks!

**Pull request merged**
