### PR TITLE
Add ppc64le support

### PR DESCRIPTION
**Pull request by mkumatag**
This PR is for supporting weave networking for ppc64le platform.

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR, @mkumatag !  I'm just running the full CI suite.

Are there cloud platforms where we can rent ppc64le hosts to test on?

**Comment by luxas** [comment]
(oops, race condition with @bboreham's comment)

**Comment by mkumatag** [comment]
@luxas yes, I did.. I created images and pushed to my own registry and deployed using steps mentioned in kubeadm, so it worked and I see dns is up and running and the node status is ready as well.

**Comment by mkumatag** [comment]
@bboreham you can get a free virtual machine [here](http://openpower.ic.unicamp.br/minicloud/), please let me know if any action required from my end!

**Comment by bboreham** [comment]
I'm ok to merge this; the bump of alpine from 3.4 to 3.6 means I won't do it in 2.0.5.

Is that change necessary for ppc64le, or you just wanted to be up to date?

**Comment by mkumatag** [comment]
ppc64le is supported only after 3.6 version.

**Comment by bboreham** [comment]
Thanks for the contribution!

**Comment by mkumatag** [comment]
@bboreham Thanks for accepting my patch, when can I expect ppc64le image in the docker hub, any timeline or release planned?

**Comment by bboreham** [comment]
@mkumatag `:latest` images should be there now; I expect we will do a 2.1 release some time in the next couple of weeks

**Pull request merged**
