### PR TITLE
Allow container names to be supplied to `weave ps`

### PR DESCRIPTION
**Pull request by bboreham**
So, `weave ps` will still show you all containers, but `weave ps mycontainer` will just show you that one.

If you give a nonexistent name you get no output, which is consistent with Unix `ps`.

### CODE REVIEW

**Comment by inercia** [comment]
+1

**Comment by rade** [comment]
I am not completely sold in this. `docker ps` doesn't take a container argument. And filtering by container id is just one 'grep' away. So what's the rationale here? Performance?

**Comment by bboreham** [comment]
I needed something like this to run smoke-tests for IPAM.

`docker ps` does have a  `--filter name=foo` option (on master).

But yes, performance. In order to grep the `weave ps` output you need the short form of the container hex ID, which needs a `docker inspect`, possibly remotely.  Also, it's much more inefficient to obtain details on every container then grep out the ones you don't need.

**Comment by rade** [comment]
ok. rationale accepted.

AFAICT, when this is fed a name, the output will contain that name, not the container id. Shouldn't the output *always* contain the id?

Docs could perhaps do with a sentence mentioning the extra functionality.

**Comment by bboreham** [comment]
While putting the hex ID in the output would be consistent, it seems rather a complex implementation to add for little benefit.  If the caller of `weave ps` knows the name of a container and doesn't know the ID, then has to do extra work to be able to match them up.

**Comment by bboreham** [comment]
Doc change added.

**Pull request merged**
