### PR TITLE
Include stylesheet in repo, update footer

### PR DESCRIPTION
**Pull request by davkal**
need because website's custom.css is fingerprinted

### CODE REVIEW

**Comment by bboreham** [comment]
1000!

**Comment by rade** [comment]
shouldn't this be against `latest_release_doc_updates` rather than `master`?

Also, I have no idea what this does.

**Comment by davkal** [comment]
@rade the docs page used to reference stylesheets from the main website, which breaks formatting sometimes when they are not in sync.

I'll redo this against `latest_release_doc_updates`.

**Comment by davkal** [comment]
Continued in #1002

**Pull request closed without merging**
