### PR TITLE
Forbid traffic to the Weave port from containers

### LINKED ISSUE #1634: Block container access to TCP 6783 & UDP 6783/6784
See https://github.com/weaveworks/weave/issues/1632#issuecomment-153714146

To prevent application containers from interfering with the weave control and data planes, especially when those are unencrypted.

### PR DESCRIPTION
**Pull request by inercia**
Fixes #1634

### CODE REVIEW

**Comment by bboreham** [comment]
Please rebase so the tests run against Docker 1.9

**Comment by inercia** [comment]
> Please rebase so the tests run against Docker 1.9

Blocked by #1675

**Comment by awh** [comment]
Apologies, the original issue was a bit muddled - it stated we needed to block UDP 6783/6784 but we also need to block TCP 6783 too (I've updated the subject to reflect this). This PR blocks TCP & UDP 6783 - can we block `$PORT+1` (the fast datapath vxlan port) as well?

**Comment by inercia** [comment]
@awh So, just to be sure we are on the same page, we need to block `6783/tcp`, `6783/udp` and `6784/udp`...

**Pull request merged**
