### PR TITLE
minor edits also added link to guide

### PR DESCRIPTION
**Pull request by abuehrle**

### CODE REVIEW

**Comment by rade** [comment]
This does not seem related to the awsvpc docs. Can/should it go on the 1.5 branch?

**Comment by abuehrle** [comment]
that's all I saw in this branch.  What else should go here? Sorry a little bit divided attention here.

**Comment by rade** [comment]
The awsvpc-docs branch adds site/using-weave/awsvpc.md, and makes a tiny change to installing-weave.md. This PR changes the latter but, AFAICT, does depend on any of the awsvpc related changes.

**Comment by bboreham** [comment]
I merged this into 1.5 and master.

**Pull request closed without merging**
