### PR TITLE
Prefix interface names with 'veth' so NetworkManager ignores them

### LINKED ISSUE #1783: `weave launch|launch-router` tickles NetworkManager
On master...

Running either `weave launch` or `weave launch-router` causes my Ubuntu NetworkManager to see new ethernet interfaces

I do not see this when running with `WEAVE_NO_FASTDP=1`

And, more importantly, I do not see this on the 1.3 branch.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #1783

### CODE REVIEW

**Comment by dpw** [comment]
(NM behaviour seems to have changed in ubuntu 15.10.  I sometimes see it produce notifications for the 'veth' prefixed netdevs created by docker.  I'm not sure what the story is.)

**Comment by awh** [comment]
Once #1758 is merged, the names `veth$BRIDGE` and `veth$DATAPATH` become available if that's preferable (see https://github.com/weaveworks/weave/issues/1783#issuecomment-164789550)

**Comment by bboreham** [comment]
I went with `veth$BRIDGE` and `vethwe$DATAPATH`; the latter so it has a vague reference to "weave"

**Comment by awh** [comment]
One has a hypen and the other doesn't...

**Comment by bboreham** [comment]
I know; we're limited in the number of characters we can have.

**Comment by bboreham** [comment]
However I found I could squeeze exactly one more in.

**Pull request merged**
