### PR TITLE
Change invariant fail on Merge() from panic to error

### PR DESCRIPTION
**Pull request by bboreham**
Improves the behaviour seen in #2083 - instead of panicking, host2 now rejects the connection and logs the error.

It does reconnect rather rapidly, which looks like a re-emergence of #953

### CODE REVIEW

**Comment by rade** [comment]
> It does reconnect rather rapidly, which looks like a re-emergence of #953

Yes, I am seeing that too. I don't think we can leave it like that.

**Comment by rade** [comment]
The backoff is certainly working in some cases, e.g. if I start a couple of peers with different `--ipalloc-rang` and then trigger IPAM.

So I am curious what is different here.

**Comment by bboreham** [comment]
We get this sequence:

````
ERRO: 2016/03/22 20:58:55.879088 ->[192.168.48.12:56188|36:ef:e0:4e:ad:3e(host2)]: connection shutting down due to error: Received new entry in my range!
INFO: 2016/03/22 20:58:55.879148 ->[192.168.48.12:56188|36:ef:e0:4e:ad:3e(host2)]: connection deleted
INFO: 2016/03/22 20:58:55.879169 Removed unreachable peer 36:ef:e0:4e:ad:3e(host2)
INFO: 2016/03/22 20:58:55.879180 Removed unreachable peer f2:d7:0d:8a:37:98(host3)
INFO: 2016/03/22 20:58:55.879217 [nameserver 0e:d8:4a:36:85:51] peer 36:ef:e0:4e:ad:3e gone
INFO: 2016/03/22 20:58:55.879232 [nameserver 0e:d8:4a:36:85:51] peer f2:d7:0d:8a:37:98 gone
INFO: 2016/03/22 20:58:55.879265 connectToTargets: removing 192.168.48.12:6783 from targets as invalid
````

(I added the last line as extra logging)

Then the next time round `checkStateAndAttemptConnections`, it's not in the `targets` so goes in as "retry now".

**Comment by rade** [comment]
> So I am curious what is different here.

#2087

**Comment by bboreham** [comment]
Is this supposed to be on 1.4 or 1.5 ?

**Comment by rade** [comment]
1.4

**Comment by bboreham** [comment]
Replaced by #2092

**Pull request closed without merging**
