### PR TITLE
Convert vendoring from git submodules to copy, using 'dep'

### PR DESCRIPTION
**Pull request by bboreham**
Initially because I didn't want to figure out the compatibility matrix by hand, although I had to do quite a lot of figuring anyway.

See individual commits for details; one notable change is that we now run `manifest-tool` from an image.

### CODE REVIEW

**Comment by brb** [comment]
Nice work!

Mind adding a small README.md (similar to the legacy `vendor/README.md`) with info how to add, update, remove deps with dep?

**Comment by bboreham** [comment]
I added the instructions to CONTRIBUTING.md since `dep` will delete anything you add in `vendor` and I couldn't think of a better place to put it.  CONTRIBUTING.md also points to the wiki, but we can't update the wiki with a PR.

**Comment by brb** [comment]
Thanks. However, I don't see the instructions, have you pushed them?

**Comment by brb** [comment]
If you rebase against origin/master, the last commit ("Update to Go 1.10.1") won't be needed.

Besides this nitpick - LGTM!

**Comment by bboreham** [comment]
I guess we should take out the 404 work-around too, since Google fixed that.

**Pull request merged**
