### PR TITLE
skip failing docker_py integration tests

### PR DESCRIPTION
**Pull request by murali-reddy**
disable test 602_proxy_docker_py_test.sh which is failing in CI

see #3680 for more details.

### CODE REVIEW

**Comment by rade** [comment]
How do you know that the tested functionality isn't in fact broken?

**Comment by murali-reddy** [comment]
There is no functional changes in weave related to docker proxy. Proxy tests are failing suddenly both on master and stable 2.5 branches. I can not figure but some thing in environment changed though docker version and docker-py is pinned to a specific version.

This PR is just to let other PR's unblock. #3680 still need to be addressed.

**Comment by rade** [comment]
> There is no functional changes in weave related to docker proxy.

Right, but these are _integration_ tests; by their nature they test functionality that cuts across components. So they may have caught a breakage elsewhere.

Have you conducted any _manual_ testing of the proxy functionality?

**Comment by murali-reddy** [comment]
> Have you conducted any manual testing of the proxy functionality?

No. Will do.

**Comment by murali-reddy** [comment]
Closing as #3689 fixed the issue

**Pull request closed without merging**
