### PR TITLE
Router and proxy run with --restart=always

### PR DESCRIPTION
**Pull request by awh**

### CODE REVIEW

**Comment by rade** [comment]
tests?

**Comment by rade** [comment]
needs rebase, including moving the `--restart` into `docker_run_options()`.

**Comment by rade** [comment]
docs?

**Comment by awh** [comment]
> moving the --restart into docker_run_options().

I cannot do this, as `docker_run_options` is used by `exec_remote` in conjunction with `--rm` and you cannot specify a restart policy with that.

**Comment by awh** [comment]
> docs?

This is happening in the operational guide PR.

**Comment by awh** [comment]
I've added a test, docs will go in the operational guide PR - PTAL, thanks.

**Comment by awh** [comment]
@rade new hotness

**Pull request merged**
