### PR TITLE
output the docker logs when docker-py fails (1.1)

### PR DESCRIPTION
**Pull request by paulbellamy**

### CODE REVIEW

**Comment by paulbellamy** [comment]
I have seen this branch fail on my dev VM, so it is not unique to circleCI.

**Comment by rade** [comment]
> I have seen this branch fail on my dev VM

i.e. it failed with the error we are chasing?

**Comment by rade** [comment]
We've seen this [fail in CI](https://circleci.com/gh/weaveworks/weave/3076) now too, but the docker log output sheds no light :( If the output isn't useful then there is no point to this PR.

**Comment by paulbellamy** [comment]
Yeah, it failed in the same test (different assertion).

**Pull request closed without merging**
