### PR TITLE
Fast datapath weave status

### LINKED ISSUE #1505: Include fast datapath information in `weave status|report`
For the purposes of support and debugging:
* `weave status connections` should display which forwarder is use per connection
* `weave report` should include the flow rules currently in effect and peer short IDs

### PR DESCRIPTION
**Pull request by awh**
This is a replacement for #1513 that is targeted against master.

Fixes #1505.

### CODE REVIEW

**Comment by dpw** [comment]
https://github.com/weaveworks/weave/commit/a553691374c2756cc3a92f0565d5afa2d4a1ba35#commitcomment-13720243

**Comment by awh** [comment]
> I'd suggest renaming this method to make it clearer it yields a name for display to the user. E.g. DisplayName.

Done.

**Comment by dpw** [comment]
The only further comment I have is to note that this doesn't put the overlay type into the gossipped connection information as shown in `weave report`.  But even if that's worth doing, it can be a separate issue.

So squash the fixup, and I'm happy to merge.

**Comment by awh** [comment]
> this doesn't put the overlay type into the gossipped connection information as shown in weave report. But even if that's worth doing, it can be a separate issue.

I did consider that, but came to the same conclusion. Fixup squashed.

**Comment by dpw** [comment]
I was wondering whether the number of flows to be shown in `weave report` might be a problem.  It could grow relatively large (easily hundreds, possibly thousands, tens of thousands might start to run into other limits).  But if we allow the JSON describing a flow to be a generous 1000 bytes, it doesn't sound problematic.  And in such cases, there might well also be hundreds or thousands of entries in the peer connections lists, so this is unlikely to present any new issues.

(I'm disappointed to find that the golang JSON encoder always encodes to an internal buffer, you cannot give it a Writer.  Even stranger, `MarshalIndent` works by generating unindented JSON, then parsing it in order to indent it.)

**Comment by awh** [comment]
> I'm disappointed

Disappointed, but not surprised I'll wager :smile:

> MarshalIndent works by generating unindented JSON, then parsing it in order to indent it.

I don't even.

**Pull request merged**
