### PR TITLE
weave-kube: allow /proc/sys/net/bridge/bridge-nf-call-iptables config to be optional

### PR DESCRIPTION
**Pull request by marun**
Targets #2581

cc: @bboreham

### CODE REVIEW

**Comment by marun** [comment]
This will enable the image to be used in an env that doesn't permit sysctl calls, but the yaml at https://git.io/weave-kube won't make use of it.  Is there an alternative to maintaining a fork of that yaml that sets the env var enabled by this pr?

**Comment by bboreham** [comment]
@marun we have some ideas around templating and configuring via parameterised web-service but are also open to suggestions.

**Comment by rade** [comment]
rather than introducing yet another knob that users have to know about, could we not turn the failure into a warning? Or perhaps try to detect the conditions when sysctl is unnecessary.

**Comment by marun** [comment]
@rade I'd be happy with a warning, and that would remove the need for custom yaml.  My requirement is that the launch script be able to work without error on a host that will be compatible (i.e. ``/proc/sys/net/bridge/bridge-nf-call-iptables=1``) but that won't allow modification from the container.  Should I revise this PR accordingly?

**Comment by rade** [comment]
I shall defer to @bboreham here.

**Comment by marun** [comment]
I imagine the issue is that early detection of an incompatible host state may be more important than supporting my niche use-case.  A knob might make more sense after all, since it's not really something general users should have to care about.

That said, is there a way to functionally test for the desired correct bridge-nf-call-iptables state?  Maybe set/detect the configuration via the fs if possible, and fall back to doing the functional check?  It's more complicated, but it would ensure correct behavior under all scenarios.

**Comment by bboreham** [comment]
There was a comparable case in #2504 where we would fail due to inability to disable TX offload, even when it was already off.

**Comment by awh** [comment]
@marun 

> Should I revise this PR accordingly?

Please do so. The behaviour should be:

1) If `/proc/sys/net/bridge/bridge-nf-call-iptables` does not exist, error
2) If `$(cat /proc/sys/net/bridge/bridge-nf-call-iptables)` does not equal `1`, attempt to set it, erroring on failure

**Comment by marun** [comment]
@awh ``/proc/sys/net/bridge/bridge-nf-call-iptables`` does not exist in the environment that I am trying to run the weave daemonset in, but the kernel configuration is nonetheless compatible.   Ideally for me, the absence of ``/proc/sys/net/bridge/bridge-nf-call-iptables`` would either result in a warning instead of an error or the check would be suppressed as per the current proposal.

**Comment by awh** [comment]
@marun ah, I misunderstood - I thought you just didn't have write permissions. In that case:

1) If `/proc/sys/net/bridge/bridge-nf-call-iptables` does not exist, echo a warning message `
﻿⁠⁠⁠⁠Cannot detect bridge-nf support - network policy and iptables mode kubeproxy may not work reliably` to stderr
2) Else if $(cat /proc/sys/net/bridge/bridge-nf-call-iptables) does not equal 1, attempt to set it, erroring on failure

**Comment by marun** [comment]
@awh I think I've done what you asked.  I don't think it's necessary to attempt to set it and err on failure explicitly since ``set -e`` should ensure an error results from any command failure.

**Comment by awh** [comment]
Hi @marun - not quite - to save any more toing and froing I've opened another PR #2659 let me know if it suffices.

**Pull request closed without merging**
