### PR TITLE
Do not overwrite negLocal entries in the cache

### PR DESCRIPTION
**Pull request by inercia**
#849 ported to master:

* Do not overwrite negLocal entries in the cache
* Unit tests

### CODE REVIEW

**Comment by rade** [comment]
Why do we need a PR for this? It should just be a merge from 0.11 to master. That's how all other 0.11 changes have been handled.

**Comment by inercia** [comment]
The reason is because master and 0.11 are very different now, while cherry picking a commit with 26 lines of code and merging it in master is trivial...

**Comment by rade** [comment]
did you try the merge?

**Comment by inercia** [comment]
No, but I've seen the output from `git diff master 0.11`...

**Comment by rade** [comment]
That is irrelevant. There's only a problem if the code on master is substantially different in the area that has changed.

**Pull request closed without merging**
