### PR TITLE
Update docs index: move WeaveDNS docs and add Getting Started Guides

### LINKED ISSUE #471: make use of DNS throughout the documentation
ATM the weaveDNS documentation is completely separate from the main documentation, with just the odd reference to it from the latter. This was desirable when weaveDNS was new and experimental, but now it actually hinders adoption.

The weave 1.0 walkthrough in #242 presents a much more integrated view of weaveDNS, and hence can serve as guidance for this issue, though we won't be able to go quite as far until a few more features have landed.

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by errordeveloper** [comment]
@fintanr could you check the paths and link titles please and let me know if those should be something different?

**Comment by rade** [comment]
I am quite sure that the design notes are rather out of date, so I am not convinced we should publish them. And if we do, we should not reference them quite so prominently. @inercia any guidance?

**Comment by errordeveloper** [comment]
> I am quite sure that the design notes are rather out of date

@rade good point, I was just hopeful...

**Comment by rade** [comment]
This does *not* close #471. #471 is about making weaveDNS an integral part of the documentation.

**Comment by errordeveloper** [comment]
[***Preview***](http://docs.weave.works/weave/move-weavedns-docs/2199c5c2735c6f9459b5ffd614038701385071fe/index.html)

**Comment by rade** [comment]
Here's what the front page should look like:

- Introduction, Installation and Example
- Features
- WeaveDNS
- Troubleshooting
- Building
- How it works
- Contact information

**Comment by errordeveloper** [comment]
[***Preview***](http://docs.weave.works/weave/move-weavedns-docs/ca4d813b71c4d327f5dc70fce9b193e077582bf8/index.html)

**Comment by rade** [comment]
LGTM

**Comment by errordeveloper** [comment]
Fogot on thing, the link from readme to weavedns docs..

**Comment by errordeveloper** [comment]
Ok, I have cherry-picked these changes onto `latest_release_doc_updates` and add d63a978.

**Pull request merged**
